const {chromium,webkit}=require('playwright');
const fs=require('fs'),path=require('path'),os=require('os');
const out=path.resolve(process.env.EVIDENCE_DIR||'godot/evidence');fs.mkdirSync(out,{recursive:true});
const url=process.env.TRIAL_URL||'http://127.0.0.1:8765';
(async()=>{let failed=0;for(const [name,type] of Object.entries({chromium,webkit})){
 const report={browser:name,os:os.platform(),arch:os.arch(),url,checks:[],errors:[],physical_phone_tested:false,audible_output_verified:false};let browser,page;
 const check=(name,ok,detail={})=>{report.checks.push({name,passed:!!ok,detail});if(!ok)throw Error(name+': '+JSON.stringify(detail))};
 try{
 browser=await type.launch({headless:true});report.version=browser.version();
 const context=await browser.newContext({viewport:{width:1304,height:1000},deviceScaleFactor:1,hasTouch:true});
 await context.addInitScript(()=>{window.__pointerTrace=[];for(const t of ['pointerdown','pointerup','pointercancel','lostpointercapture'])document.addEventListener(t,e=>{window.__pointerTrace.push({type:t,id:e.pointerId,target:e.target.dataset?.action,time:performance.now()});if(window.__pointerTrace.length>60)window.__pointerTrace.shift()},true);window.__audioContexts=[];const Original=window.AudioContext||window.webkitAudioContext;if(Original){const Wrapped=new Proxy(Original,{construct(Target,args){const instance=new Target(...args);window.__audioContexts.push(instance);return instance}});window.AudioContext=Wrapped;if(window.webkitAudioContext)window.webkitAudioContext=Wrapped;}});
 page=await context.newPage();page.on('pageerror',e=>report.errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text())});
 const began=Date.now();await page.goto(url);await page.waitForFunction(()=>M1Bridge.state?.phase==='ready',{},{timeout:90000});report.ready_ms=Date.now()-began;
 const state=()=>page.evaluate(()=>M1Bridge.state);
 check('engine ready and fixed 640×360 viewport',(await state()).viewport.join(',')==='640,360',await state());
 await page.locator('#start').click();await page.waitForFunction(()=>M1Bridge.state.phase==='running'&&M1Bridge.state.grounded);await page.waitForTimeout(350);
 await page.locator('#canvas').screenshot({path:path.join(out,`${name}-canvas-2x.png`)});
 await page.screenshot({path:path.join(out,`${name}-desktop.png`),fullPage:true});
 const dimensions=await page.locator('#canvas').evaluate(c=>({width:c.width,height:c.height,cssWidth:c.getBoundingClientRect().width,cssHeight:c.getBoundingClientRect().height}));check('desktop integer 2x display',dimensions.width===640&&dimensions.height===360&&dimensions.cssWidth===1280&&dimensions.cssHeight===720,dimensions);
 let before=await state();await page.keyboard.down('ArrowRight');await page.waitForTimeout(250);await page.keyboard.up('ArrowRight');await page.waitForTimeout(200);check('keyboard right and release braking',(await state()).x>before.x+20&&Math.abs((await state()).vx)<1,{before,after:await state()});
 before=await state();await page.keyboard.down('a');await page.waitForTimeout(250);await page.keyboard.up('a');await page.waitForTimeout(200);check('physical A moves left',(await state()).x<before.x-20);
 async function reset(){await page.locator('#reset').click();await page.waitForFunction(()=>M1Bridge.state.grounded&&M1Bridge.state.jumps===0&&M1Bridge.state.tick>35&&M1Bridge.state.feet>294);await page.waitForTimeout(200)}
 async function jump(ms){await reset();const start=await state();await page.evaluate(()=>M1Bridge.history=[]);await page.keyboard.down('ArrowUp');if(ms)await page.waitForTimeout(ms);await page.keyboard.up('ArrowUp');await page.waitForTimeout(1000);const h=await page.evaluate(()=>M1Bridge.history);return{height:start.feet-Math.min(...h.map(s=>s.feet)),jumps:(await state()).jumps,grounded:(await state()).grounded}}
 const short=await jump(35),held=await jump(350),quick=await jump(0);check('short and held keyboard jumps have different heights',short.jumps===1&&held.jumps===1&&held.height>short.height+10,{short,held});check('quick key down/up is not lost',quick.jumps===1&&quick.grounded,quick);
 await reset();await page.keyboard.down('Space');await page.waitForTimeout(200);check('keyboard filming active',(await state()).recording);await page.keyboard.up('Space');await page.waitForTimeout(150);check('keyboard filming release',!(await state()).recording);
 await reset();await page.keyboard.press('r');await page.waitForTimeout(250);check('full-film reload does not spend a reel',(await state()).spares===2&&(await state()).reloads===0);
 await page.keyboard.down('Space');await page.waitForTimeout(500);await page.keyboard.up('Space');await page.waitForTimeout(150);before=await state();check('filming drains finite stock',before.film<before.film_capacity);
 await page.keyboard.down('r');await page.waitForTimeout(250);check('reload spends one spare and suspends filming',(await state()).spares===1&&(await state()).reload_left>0&&!(await state()).recording);await page.waitForTimeout(800);await page.keyboard.up('r');check('held reload completes once at full film',(await state()).film===(await state()).film_capacity&&(await state()).reloads===1&&(await state()).spares===1);
 // Real browser touch events in Chromium, portable DOM pointer events in WebKit (explicitly identified).
 await reset();await page.setViewportSize({width:844,height:390});await page.waitForTimeout(200);let touch;
 if(name==='chromium'){
 const session=await context.newCDPSession(page);const pts={};touch=async(action,id,pressed)=>{if(pressed){const r=await page.locator(`[data-action="${action}"]`).boundingBox();pts[id]={x:r.x+r.width/2,y:r.y+r.height/2,id};await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[pts[id]]})}else{const ended=pts[id];delete pts[id];await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:ended?[ended]:[]})}};report.touch_method='Chromium CDP multi-touch input';
 }else{touch=async(action,id,pressed)=>{await page.locator(`[data-action="${action}"]`).evaluate((b,{id,pressed})=>{b.setPointerCapture=()=>{};b.dispatchEvent(new PointerEvent(pressed?'pointerdown':'pointerup',{pointerId:id,pointerType:'touch',bubbles:true,cancelable:true}))},{id,pressed})};report.touch_method='WebKit DOM pointer events; hardware delivery not certified'}
 before=await state();await touch('move_right',1,true);await touch('record',2,true);await page.waitForTimeout(160);await touch('jump',3,true);await page.waitForTimeout(40);await touch('jump',3,false);await page.waitForTimeout(160);const multi=await state();check('move + film + jump simultaneously',multi.x>before.x+20&&multi.recording&&multi.jumps===1,{before,multi});await touch('record',2,false);await page.waitForTimeout(150);check('releasing film preserves held direction',!(await state()).recording&&(await state()).actions.move_right,{state:await state(),trace:await page.evaluate(()=>__pointerTrace),held:await page.locator('[data-action]').evaluateAll(bs=>bs.map(b=>({action:b.dataset.action,held:b.dataset.held})))});await touch('move_right',1,false);await page.waitForTimeout(250);check('touch release brakes',Math.abs((await state()).vx)<1);
 await reset();await touch('record',7,true);await page.waitForTimeout(400);await touch('record',7,false);await touch('move_right',8,true);await touch('reload',9,true);await touch('reload',9,false);await page.waitForTimeout(200);check('quick touch reload works while moving',(await state()).reload_left>0&&(await state()).actions.move_right);await touch('move_right',8,false);await page.waitForTimeout(650);check('touch reload restores full film',(await state()).film===(await state()).film_capacity&&(await state()).reloads===1);
 await reset();await page.keyboard.down('ArrowRight');await page.waitForTimeout(360);await page.keyboard.up('ArrowRight');await page.waitForTimeout(200);check('world pickup adds a spare',(await state()).spares===3&&(await state()).pickups===2);
 await reset();await touch('move_right',4,true);await page.waitForTimeout(100);await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await page.waitForTimeout(200);before=await state();check('blur pauses and clears velocity',before.phase==='paused'&&before.vx===0);await page.waitForTimeout(200);check('paused simulation does not advance',(await state()).tick===before.tick);await touch('move_right',4,false);await page.locator('#start').click();await page.waitForTimeout(250);check('resume has no stuck movement',Math.abs((await state()).vx)<1);
 await reset();before=await state();await page.evaluate(()=>{M1Bridge.send('jump',true);M1Bridge.send('pause',true)});await page.waitForTimeout(150);await page.locator('#start').click();await page.waitForTimeout(250);check('pause clears a queued jump before resume',(await state()).jumps===before.jumps&&!(await state()).actions.jump);
 await touch('record',6,true);await page.evaluate(()=>window.dispatchEvent(new Event('orientationchange')));await touch('record',6,false);await page.waitForTimeout(150);check('rotation pauses and clears filming',(await state()).phase==='paused'&&!(await state()).recording);await page.locator('#start').click();
 for(const [w,h] of [[844,390],[390,844],[1024,768]]){await page.setViewportSize({width:w,height:h});await page.waitForTimeout(200);const fit=await page.evaluate(()=>{const r=document.querySelector('canvas').getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height,overflow:document.documentElement.scrollWidth>innerWidth,viewport:M1Bridge.state.viewport}});check(`fit ${w}×${h}`,!fit.overflow&&fit.x>=0&&fit.x+fit.w<=w+1&&Math.abs(fit.w/fit.h-640/360)<.01&&fit.viewport.join(',')==='640,360',fit);await page.screenshot({path:path.join(out,`${name}-${w}x${h}.png`),fullPage:true})}
 await page.locator('#sound').click();await page.waitForTimeout(150);check('sound toggle off',!(await state()).audio_enabled);await page.locator('#sound').click();await page.waitForTimeout(250);const audio=await page.evaluate(()=>__audioContexts.map(c=>({state:c.state,time:c.currentTime,sampleRate:c.sampleRate})));check('audio context running after user activation',audio.some(c=>c.state==='running'&&c.time>0),audio);report.audio=audio;
 await page.locator('#install').click();check('shortcut fallback is honest about offline support',(await page.locator('#notice').textContent()).includes('Offline play is not included'));
 await page.locator('#fullscreen').click();await page.waitForTimeout(300);const full=await page.evaluate(()=>({active:!!document.fullscreenElement,notice:document.getElementById('notice').textContent}));check('fullscreen or visible fallback',full.active||full.notice.includes('Full screen is unavailable'),full);if(full.active)await page.evaluate(()=>document.exitFullscreen());
 // Exercise the unsupported fullscreen path independently.
 await page.evaluate(()=>{document.getElementById('frame').requestFullscreen=undefined});await page.locator('#fullscreen').click();check('unsupported fullscreen remains usable',(await page.locator('#notice').textContent()).includes('Rotate to landscape'));
 await page.waitForTimeout(1500);report.performance=await state();report.resources=await page.evaluate(()=>performance.getEntriesByType('resource').map(r=>({name:r.name.split('/').pop(),duration:r.duration,transferSize:r.transferSize,decodedBodySize:r.decodedBodySize})));
 report.gl_errors=[];for(let i=0;i<12;i++){await page.waitForTimeout(100);report.gl_errors.push(await page.evaluate(()=>document.querySelector('canvas').getContext('webgl2').getError()))}check('sustained GL error polling is clean',report.gl_errors.every(x=>x===0),report.gl_errors);
 check('no browser script or engine console errors',report.errors.length===0,report.errors);
 }catch(e){report.failure=String(e);failed++;if(page)await page.screenshot({path:path.join(out,`${name}-failure.png`),fullPage:true}).catch(()=>{});}finally{if(browser)await browser.close();report.passed=report.checks.filter(c=>c.passed).length;report.failed=report.failure?1:0;fs.writeFileSync(path.join(out,`${name}-browser.json`),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));}}
 if(require("fs").existsSync("preview-candidate/courtyard-01/index.html")){try{for(const [tag,res] of [["720",[1280,720]],["1080",[1920,1080]]])require("child_process").execFileSync(process.execPath,["godot/tests/courtyard_browser.cjs"],{stdio:"inherit",env:{...process.env,COURTYARD_ROOT:"preview-candidate/courtyard-"+tag,COURTYARD_TAG:"courtyard-"+tag,COURTYARD_RESOLUTION:JSON.stringify(res)}});}catch(e){failed++;}}
 if(require("fs").existsSync("preview-candidate/gothic-chapter-01/index.html")){try{require("child_process").execFileSync(process.execPath,["godot/tests/chapter_browser.cjs"],{stdio:"inherit"});}catch(e){failed++;}}
 process.exitCode=failed?1:0;
})().catch(e=>{console.error(e);process.exit(1)});
