extends SceneTree
var checks: Array = []
func _initialize() -> void: run.call_deferred()
func check(label: String, ok: bool, detail: Variant = null) -> void:
	checks.append({"name":label,"passed":ok,"detail":detail})
	print(("PASS " if ok else "FAIL ")+label+" "+str(detail))
func wait(seconds: float) -> void: await create_timer(seconds).timeout
func run() -> void:
	var foe = preload("res://scripts/guardian_encounter.gd").new()
	for i in range(40): foe.advance(0.02,Vector2(390,230),true,1)
	check("Filming guarded enemy gives no exposure",foe.exposure==0 and foe.phase=="windup")
	for i in range(44): foe.advance(0.02,Vector2(390,180),false,1)
	var hit := false
	for i in range(20): hit = foe.advance(0.02,Vector2(390,180),false,1).hit or hit
	check("Jump clears the low sweep",not hit and foe.phase=="exposed")
	foe.advance(0.3,Vector2(390,230),true,-1)
	check("Camera must face exposed enemy",foe.exposure==0)
	for i in range(66): foe.advance(0.02,Vector2(390,230),true,1)
	check("Filming exposed enemy captures it",foe.phase=="captured")
	foe.reset()
	foe.phase="exposed"
	foe.clock=1.79
	foe.advance(0.04,Vector2(390,230),true,1)
	check("Exposure window expires even while filming",foe.phase=="watch" and foe.exposure==0)
	foe.phase="attack"
	foe.x=425
	var first: Dictionary = foe.advance(0.01,Vector2(390,230),false,1)
	var second: Dictionary = foe.advance(0.01,Vector2(390,230),false,1)
	check("Sweep damages once, not every frame",first.hit and not second.hit)
	var room = load("res://scenes/gothic_room.tscn").instantiate()
	root.add_child(room)
	room._command("resume")
	await wait(0.4)
	check("Courtyard starts on the upper bridge",room.player.is_on_floor() and absf(room.player.position.y-230)<1,room.player.position)
	room.player.reset_at(Vector2(244,230))
	await wait(0.25)
	Input.action_press("move_right")
	Input.action_press("jump")
	await wait(0.70)
	Input.action_release("jump")
	await wait(0.20)
	Input.action_release("move_right")
	await wait(0.15)
	check("Authored bridge gap is jumpable",room.player.position.x>340 and room.player.is_on_floor() and absf(room.player.position.y-230)<1,room.player.position)
	check("Crossing activates checkpoint",room._checkpoint_active)
	room._command("reset")
	check("Retry restores checkpoint and supplies",room.player.position.x==365 and room.stock.spares==2 and room.stock.film==12)
	room.player.reset_at(Vector2(178,335))
	await wait(0.3)
	check("Crypt reel can be collected",room.stock.spares==3 and room._pickups==1)
	room.player.reset_at(Vector2(285,342))
	await wait(0.25)
	for expected_y in [310.0,276.0]:
		Input.action_press("jump")
		await wait(0.70)
		Input.action_release("jump")
		await wait(0.12)
		check("Crypt return step at %s is reachable" % expected_y,absf(room.player.position.y-expected_y)<1,room.player.position)
	Input.action_press("jump")
	Input.action_press("move_right")
	await wait(0.29)
	Input.action_release("move_right")
	await wait(0.41)
	Input.action_release("jump")
	await wait(0.15)
	check("Third crypt step is reachable",absf(room.player.position.y-246)<1,room.player.position)
	Input.action_press("jump")
	Input.action_press("move_right")
	await wait(0.65)
	Input.action_release("jump")
	Input.action_release("move_right")
	await wait(0.2)
	check("Crypt route returns to upper bridge",room.player.position.x>340 and absf(room.player.position.y-230)<1,room.player.position)
	room.player.reset_at(Vector2(285,275))
	await wait(0.2)
	Input.action_press("drop")
	await wait(0.35)
	Input.action_release("drop")
	await wait(0.1)
	check("Down drops through crypt step",room.player.position.y>300,room.player.position)
	room.player.reset_at(Vector2(365,230))
	await wait(0.2)
	Input.action_press("drop")
	await wait(0.35)
	Input.action_release("drop")
	check("Down cannot fall through solid bridge",absf(room.player.position.y-230)<1,room.player.position)
	room.stock.advance(2.0,true)
	room.stock.start_reload()
	room._command("pause")
	var remaining: float = room.stock.reload_left
	await wait(0.4)
	check("Pause freezes reload",room.stock.reload_left==remaining)
	room._command("resume")
	await wait(0.8)
	check("Resume completes committed reload",room.stock.film==12 and room.stock.reloads==1)
	room._command("reset")
	room.guardian.phase="captured"
	room._gate_body.collision_layer=0
	room.player.reset_at(Vector2(616,230))
	await wait(0.1)
	check("Captured guardian allows room completion",room._completed and room._phase=="complete")
	room._command("review")
	check("Action review clears completion overlay",not room._completed and room._phase=="review")
	room._command("reset")
	check("Retry resets capture and restores gate",not room._completed and room.guardian.phase=="watch" and room._gate_body.collision_layer==1)
	var failures := checks.filter(func(c): return not c.passed).size()
	var file := FileAccess.open("res://tests/latest-courtyard-results.json",FileAccess.WRITE)
	file.store_string(JSON.stringify({"passed":checks.size()-failures,"failed":failures,"checks":checks,"physical_phone_tested":false},"  "))
	file.close()
	room._ambient.stream_paused = false
	room._ambient.stop()
	room._ambient.stream = null
	await wait(0.15)
	room.free()
	foe = null
	await process_frame
	quit(1 if failures else 0)
