(()=>{
const C=window.MWCAM_CONFIG||{};const A=window.MWCAM_ASSETS||{};
const input={left:false,right:false,jump:false,beam:false};
let audioCtx=null,musicTimer=null;
function ac(){if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}
function tone(f,d=.08,type='square',v=.018,delay=0){const a=ac(),o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.setValueAtTime(f,a.currentTime+delay);g.gain.setValueAtTime(v,a.currentTime+delay);g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+delay+d);o.connect(g);g.connect(a.destination);o.start(a.currentTime+delay);o.stop(a.currentTime+delay+d)}
function noise(d=.08,v=.025){const a=ac(),b=a.createBuffer(1,a.sampleRate*d,a.sampleRate),x=b.getChannelData(0);for(let i=0;i<x.length;i++)x[i]=(Math.random()*2-1)*(1-i/x.length);const s=a.createBufferSource(),g=a.createGain();s.buffer=b;g.gain.value=v;s.connect(g);g.connect(a.destination);s.start()}
function sfx(k){if(k==='jump'){tone(190,.08);tone(295,.07,'square',.014,.04)}if(k==='beam')tone(76,.09,'sawtooth',.009);if(k==='capture'){tone(330,.07,'triangle',.035);tone(495,.09,'triangle',.028,.06);tone(742,.14,'triangle',.02,.13)}if(k==='hurt'){noise(.11,.035);tone(68,.16,'sawtooth',.025)}if(k==='land')tone(44,.035,'square',.008)}
function music(){clearInterval(musicTimer);let n=0;const seq=[0,3,7,10,12,10,8,3,0,5,8,12,15,12,8,5],bass=[0,0,-2,-2,-5,-5,-7,-7];musicTimer=setInterval(()=>{const r=55*Math.pow(2,seq[n%seq.length]/12);tone(r,.33,'triangle',.008);if(!(n%2))tone(r*2,.16,'square',.004);if(!(n%4))tone(41.2*Math.pow(2,bass[(n/2)%bass.length|0]/12),.16,'square',.007);n++},225)}
function makeFallback(scene,key,kind){const w=kind==='hero'?74:70,h=kind==='knight'?112:100,t=scene.add.renderTexture(0,0,w,h).setVisible(false),g=scene.add.graphics();const skin=kind==='skeleton'?0xd9d4c8:kind==='ghoul'?0x8aa078:kind==='knight'?0x676b70:0xc78d68;g.fillStyle(0x11141a).fillEllipse(w/2,h-8,48,9);if(kind==='skeleton'){g.lineStyle(7,skin).strokeLineShape(new Phaser.Geom.Line(34,28,34,73));g.strokeCircle(34,18,12);g.strokeLineShape(new Phaser.Geom.Line(34,40,16,57));g.strokeLineShape(new Phaser.Geom.Line(34,40,52,57));g.strokeLineShape(new Phaser.Geom.Line(34,70,20,96));g.strokeLineShape(new Phaser.Geom.Line(34,70,51,96))}else{g.fillStyle(kind==='hero'?0x263343:kind==='ghoul'?0x4b4e3e:0x3f4247).fillEllipse(34,60,35,66);g.fillStyle(skin).fillCircle(34,21,14);g.fillStyle(0x19191c).fillRect(22,8,26,7);g.fillStyle(kind==='hero'?0x191c20:0x303035).fillRect(13,38,10,46).fillRect(46,38,10,46);g.fillStyle(0x17191e).fillRect(20,85,12,24).fillRect(39,85,12,24);if(kind==='hero'){g.fillStyle(0x0a0c10).fillRect(42,31,27,17);g.fillStyle(0x67717b).fillRect(63,35,9,9);g.fillStyle(0x9ba2a7).fillRect(48,25,8,8)}if(kind==='knight'){g.lineStyle(3,0x92979b).strokeCircle(34,21,16);g.fillStyle(0x7b2028).fillRect(52,41,12,45)}}t.draw(g);t.saveTexture(key);g.destroy();t.destroy()}
class BlackHouse extends Phaser.Scene{
constructor(){super('BlackHouse');this.health=C.player?.maxHealth||5;this.captured=0;this.film=100;this.beamPulse=0;this.dead=false}
preload(){if(A.courtyard)this.load.image('courtyard',A.courtyard);if(A.hero)this.load.spritesheet('heroReal',A.hero,{frameWidth:106,frameHeight:126});if(A.skeleton)this.load.spritesheet('skeletonReal',A.skeleton,{frameWidth:128,frameHeight:144});if(A.ghoul)this.load.spritesheet('ghoulReal',A.ghoul,{frameWidth:120,frameHeight:140});if(A.knight)this.load.spritesheet('knightReal',A.knight,{frameWidth:134,frameHeight:149})}
create(){this.physics.world.setBounds(0,0,4200,720);this.cameras.main.setBounds(0,0,4200,720);this.cameras.main.setBackgroundColor('#070910');
if(!this.textures.exists('heroReal'))makeFallback(this,'heroFallback','hero');if(!this.textures.exists('skeletonReal'))makeFallback(this,'skeletonFallback','skeleton');if(!this.textures.exists('ghoulReal'))makeFallback(this,'ghoulFallback','ghoul');if(!this.textures.exists('knightReal'))makeFallback(this,'knightFallback','knight');
this.makeWorld();this.makeAnims();this.makePlayer();this.makeEnemies();this.makeFX();this.makeInput();this.makeCamera();this.updateHud();
}
makeWorld(){if(this.textures.exists('courtyard')){for(let i=0;i<5;i++){const far=this.add.image(i*960,355,'courtyard').setOrigin(0,.5).setDisplaySize(960,498).setScrollFactor(.18).setAlpha(.42).setTint(0x5e6b89);far.setDepth(-20)}for(let i=0;i<5;i++){const mid=this.add.image(i*960,390,'courtyard').setOrigin(0,.5).setDisplaySize(960,498).setScrollFactor(.48).setAlpha(.30).setTint(0x8790a3);mid.setDepth(-10)}}
const moon=this.add.circle(1030,120,85,0xcbd9f5,.74).setScrollFactor(.07).setDepth(-30);this.add.circle(1060,95,78,0x0b1021,.93).setScrollFactor(.07).setDepth(-29);
for(let i=0;i<22;i++){this.add.ellipse(i*240,475+(i%3)*33,430,60,0xb5c0d0,.025).setScrollFactor(.35+(i%3)*.08).setDepth(-5)}
this.solids=this.physics.add.staticGroup();const floor=this.add.rectangle(2100,650,4200,140,0x111116).setAlpha(.94);this.physics.add.existing(floor,true);this.solids.add(floor);for(let x=0;x<4200;x+=80){this.add.rectangle(x+40,583,80,18,0x322d35).setStrokeStyle(1,0x5b505a).setDepth(2);this.add.rectangle(x+13,600+(x/80%2)*6,23,8,0x1f1b21).setDepth(2);this.add.rectangle(x+53,596+((x/80+1)%2)*6,21,7,0x241f25).setDepth(2)}
const platforms=[[640,510,240],[1120,450,280],[1660,515,260],[2220,430,330],[2850,500,260],[3440,445,300],[3880,525,190]];platforms.forEach(([x,y,w])=>{const p=this.add.rectangle(x,y,w,24,0x2b2630).setStrokeStyle(2,0x71606e).setDepth(3);this.physics.add.existing(p,true);this.solids.add(p);for(let q=0;q<w;q+=42)this.add.rectangle(x-w/2+q+18,y+10,31,5,0x17141a).setDepth(3)});
for(let i=0;i<18;i++){const x=180+i*235;this.add.rectangle(x,560,20,78,0x35303a).setStrokeStyle(2,0x5b535f).setDepth(1);this.add.ellipse(x,520,48,21,0x45404a).setStrokeStyle(2,0x6d6570).setDepth(1)}
for(let i=0;i<16;i++){const x=110+i*265;this.add.rectangle(x,542,5,35,0x584638).setDepth(4);this.add.circle(x,521,6,0xffc56f,.95).setDepth(4);this.add.circle(x,521,28,0xff9a48,.08).setBlendMode(Phaser.BlendModes.ADD).setDepth(3)}
}
makeAnims(){const specs=[['heroReal','hero-walk',6],['skeletonReal','skeleton-walk',6],['ghoulReal','ghoul-walk',6],['knightReal','knight-walk',6]];specs.forEach(([tex,key,n])=>{if(this.textures.exists(tex)&&!this.anims.exists(key))this.anims.create({key,frames:this.anims.generateFrameNumbers(tex,{start:0,end:n-1}),frameRate:key==='hero-walk'?10:7,repeat:-1})})}
makePlayer(){const tex=this.textures.exists('heroReal')?'heroReal':'heroFallback';this.player=this.physics.add.sprite(170,520,tex,0).setDepth(8).setCollideWorldBounds(true);if(tex==='heroReal')this.player.setScale(.62);this.player.body.setSize(tex==='heroReal'?48:38,tex==='heroReal'?104:87).setOffset(tex==='heroReal'?29:18,tex==='heroReal'?18:10);this.physics.add.collider(this.player,this.solids);this.player.setData('inv',false)}
makeEnemies(){this.enemies=this.physics.add.group();const S=C.level?.spawns||[{type:'skeleton',x:760,y:515},{type:'ghoul',x:1280,y:515},{type:'skeleton',x:1760,y:510},{type:'knight',x:2380,y:500},{type:'ghoul',x:3000,y:500},{type:'knight',x:3620,y:500}];S.forEach(s=>this.spawn(s));this.physics.add.collider(this.enemies,this.solids);this.physics.add.overlap(this.player,this.enemies,(p,e)=>this.hurt(e));this.time.addEvent({delay:550,loop:true,callback:()=>this.enemyThink()})}
spawn(s){const real=this.textures.exists(s.type+'Real'),tex=real?s.type+'Real':s.type+'Fallback';const e=this.enemies.create(s.x,s.y,tex,0).setDepth(8);e.setScale(real?(s.type==='knight'?.64:.60):1);e.body.setSize(real?52:40,real?(s.type==='knight'?112:102):88).setOffset(real?35:15,real?20:8);e.setData('type',s.type);e.setData('capture',0);e.setData('resistance',C.enemies?.[s.type]?.resistance||1);e.setData('baseScale',e.scaleX);e.setData('stunned',0);return e}
makeFX(){this.beam=this.add.graphics().setDepth(7);this.rings=this.add.graphics().setDepth(7);this.particles=this.add.particles(0,0,'__DEFAULT',{speed:{min:30,max:120},lifespan:380,quantity:0,scale:{start:.055,end:0},blendMode:'ADD'}).setDepth(10)}
makeInput(){this.cursors=this.input.keyboard.createCursorKeys();this.keys=this.input.keyboard.addKeys('A,D,W,SPACE,SHIFT');document.querySelectorAll('#touch button').forEach(b=>{const k=b.dataset.k;const on=e=>{e.preventDefault();ac();input[k]=true};const off=e=>{e.preventDefault();input[k]=false};b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off);b.addEventListener('pointerleave',off)});document.getElementById('fullscreen').onclick=()=>{const el=document.documentElement;(el.requestFullscreen||el.webkitRequestFullscreen)?.call(el);ac()};window.addEventListener('blur',()=>Object.keys(input).forEach(k=>input[k]=false));document.body.addEventListener('pointerdown',()=>{ac();if(!musicTimer)music()},{once:true})}
makeCamera(){this.cameras.main.startFollow(this.player,true,.09,.09,-170,35);this.cameras.main.roundPixels=true;this.cameras.main.setDeadzone(120,70)}
enemyThink(){if(this.dead)return;this.enemies.children.iterate(e=>{if(!e?.active)return;if(e.getData('stunned')>0){e.setVelocityX(0);return}const dx=this.player.x-e.x,dist=Math.abs(dx);const speed=C.enemies?.[e.getData('type')]?.speed||45;if(dist<520){e.setVelocityX(Phaser.Math.Clamp(dx*.22,-speed,speed));e.setFlipX(dx<0);const anim=e.getData('type')+'-walk';if(this.anims.exists(anim))e.play(anim,true)}else e.setVelocityX(Math.sin((this.time.now+e.x)*.0015)*12)})}
hurt(e){if(this.player.getData('inv')||this.dead)return;this.player.setData('inv',true);this.health--;sfx('hurt');this.player.setVelocityY(-210);this.player.setVelocityX(this.player.x<e.x?-210:210);this.cameras.main.shake(140,.007);this.tweens.add({targets:this.player,alpha:.2,yoyo:true,repeat:5,duration:65,onComplete:()=>{this.player.alpha=1;this.player.setData('inv',false)}});if(this.health<=0)this.respawn();this.updateHud()}
respawn(){this.dead=true;this.time.delayedCall(350,()=>{this.health=C.player?.maxHealth||5;this.player.setPosition(170,500).setVelocity(0,0);this.dead=false;this.updateHud()})}
update(time,dtMs){if(this.dead)return;const dt=Math.min(dtMs/1000,.05),left=input.left||this.cursors.left.isDown||this.keys.A.isDown,right=input.right||this.cursors.right.isDown||this.keys.D.isDown,jump=input.jump||this.cursors.up.isDown||this.keys.W.isDown,beam=input.beam||this.cursors.space.isDown||this.keys.SPACE.isDown,speed=C.player?.speed||205;if(left){this.player.setVelocityX(-speed);this.player.setFlipX(true)}else if(right){this.player.setVelocityX(speed);this.player.setFlipX(false)}else this.player.setVelocityX(this.player.body.velocity.x*.70);const moving=Math.abs(this.player.body.velocity.x)>15;if(moving&&this.anims.exists('hero-walk'))this.player.play('hero-walk',true);else if(this.player.anims)this.player.anims.stop();if(jump&&this.player.body.blocked.down&&!this.jumpLatch){this.player.setVelocityY(C.player?.jumpVelocity||-405);sfx('jump');this.jumpLatch=true}if(!jump)this.jumpLatch=false;if(beam&&this.film>0)this.capture(dt);else{this.beam.clear();this.rings.clear();this.enemies.children.iterate(e=>{if(e?.active)e.setData('stunned',Math.max(0,e.getData('stunned')-dt))});this.film=Math.min(100,this.film+dt*6)}this.updateHud()}
capture(dt){this.film=Math.max(0,this.film-dt*9);const face=this.player.flipX?-1:1,lensX=this.player.x+face*44,lensY=this.player.y-17,range=C.capture?.range||430,half=C.capture?.spread||145,endX=lensX+face*range;this.beam.clear();this.rings.clear();this.beam.fillStyle(C.capture?.beamColor||0x8ce8ff,C.capture?.beamAlpha||.13);this.beam.lineStyle(2,0xcaf5ff,.55);this.beam.beginPath().moveTo(lensX,lensY).lineTo(endX,lensY-half).lineTo(endX,lensY+half).closePath().fillPath().strokePath();for(let r=70;r<range;r+=84){const t=r/range;this.rings.lineStyle(1,0xbceeff,.18);this.rings.strokeEllipse(lensX+face*r,lensY,12+52*t,34+half*1.15*t)}if(this.time.now-this.beamPulse>115){sfx('beam');this.beamPulse=this.time.now}
this.enemies.children.iterate(e=>{if(!e?.active)return;const dx=e.x-lensX,dy=e.y-lensY,forward=dx*face;if(forward<=5||forward>range)return;const allowed=(forward/range)*half+20;if(Math.abs(dy)>allowed)return;e.setData('stunned',.15);const resistance=e.getData('resistance')||1,pull=(C.capture?.pullStrength||310)/resistance;e.setVelocityX(-Math.sign(dx)*pull*Math.max(.25,1-forward/range));e.setVelocityY(Phaser.Math.Clamp(-dy*2.5,-100,100));let cap=e.getData('capture')+dt*(C.capture?.baseRate||.72)/resistance;cap=Math.min(1.2,cap);e.setData('capture',cap);const base=e.getData('baseScale')||1,shrink=Phaser.Math.Clamp(1-cap*.36,.46,1);e.setScale(base*shrink);e.setAlpha(1-cap*.34);e.setAngle(Math.sin(this.time.now*.025+e.x)*cap*5);if(Math.random()<.16)this.particles.emitParticleAt(e.x,e.y,1);if(cap>=1||Phaser.Math.Distance.Between(e.x,e.y,lensX,lensY)<38)this.captureEnemy(e)})}
captureEnemy(e){if(!e.active)return;this.captured++;sfx('capture');this.cameras.main.flash(90,120,210,255,false);this.cameras.main.shake(90,.004);this.particles.emitParticleAt(e.x,e.y,14);e.disableBody(true,true);this.updateHud()}
updateHud(){const s=document.getElementById('status');if(s)s.innerHTML=`THE BLACK HOUSE &nbsp; <span class="life">LIFE ${'■'.repeat(Math.max(0,this.health))}${'□'.repeat(Math.max(0,(C.player?.maxHealth||5)-this.health))}</span> &nbsp; <span class="film">FILM ${Math.round(this.film)}%</span> &nbsp; CAPTURED ${this.captured}`}
}
new Phaser.Game({type:Phaser.AUTO,parent:'game',width:1280,height:720,backgroundColor:'#06070b',pixelArt:true,roundPixels:true,physics:{default:'arcade',arcade:{gravity:{y:900},debug:false}},scale:{mode:Phaser.Scale.RESIZE,autoCenter:Phaser.Scale.CENTER_BOTH},scene:[BlackHouse],render:{antialias:false,pixelArt:true,roundPixels:true}});
})();