(()=>{
const C=window.MWCAM_CONFIG||{};
const A=window.MWCAM_ASSETS||{};
const input={left:false,right:false,jump:false,beam:false};
let audioCtx=null,musicTimer=null;
function ac(){if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx}
function tone(f,d=.08,type='square',v=.018,delay=0){const a=ac(),o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.setValueAtTime(f,a.currentTime+delay);g.gain.setValueAtTime(v,a.currentTime+delay);g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+delay+d);o.connect(g);g.connect(a.destination);o.start(a.currentTime+delay);o.stop(a.currentTime+delay+d)}
function noise(d=.08,v=.025){const a=ac(),b=a.createBuffer(1,a.sampleRate*d,a.sampleRate),x=b.getChannelData(0);for(let i=0;i<x.length;i++)x[i]=(Math.random()*2-1)*(1-i/x.length);const s=a.createBufferSource(),g=a.createGain();s.buffer=b;g.gain.value=v;s.connect(g);g.connect(a.destination);s.start()}
function sfx(k){if(k==='jump'){tone(190,.08);tone(295,.07,'square',.014,.04)}if(k==='beam')tone(76,.09,'sawtooth',.009);if(k==='capture'){tone(330,.07,'triangle',.035);tone(495,.09,'triangle',.028,.06);tone(742,.14,'triangle',.02,.13)}if(k==='hurt'){noise(.11,.035);tone(68,.16,'sawtooth',.025)}if(k==='empty'){tone(62,.09,'square',.02);tone(48,.12,'square',.016,.07)}if(k==='checkpoint'){tone(220,.12,'triangle',.02);tone(330,.16,'triangle',.018,.08)}if(k==='clear'){[262,330,392,523,659].forEach((f,i)=>tone(f,.24,'triangle',.028,i*.08))}}
function music(){clearInterval(musicTimer);let n=0;const seq=[0,3,7,10,12,10,8,3,0,5,8,12,15,12,8,5],bass=[0,0,-2,-2,-5,-5,-7,-7];musicTimer=setInterval(()=>{const r=55*Math.pow(2,seq[n%seq.length]/12);tone(r,.33,'triangle',.007);if(!(n%2))tone(r*2,.16,'square',.0035);if(!(n%4))tone(41.2*Math.pow(2,bass[(n/2)%bass.length|0]/12),.16,'square',.006);n++},225)}
function makeFallback(scene,key,kind){const w=kind==='hero'?74:70,h=kind==='knight'?112:100,t=scene.add.renderTexture(0,0,w,h).setVisible(false),g=scene.add.graphics();const skin=kind==='skeleton'?0xd9d4c8:kind==='ghoul'?0x8aa078:kind==='knight'?0x676b70:0xc78d68;g.fillStyle(0x11141a).fillEllipse(w/2,h-8,48,9);if(kind==='skeleton'){g.lineStyle(7,skin).strokeLineShape(new Phaser.Geom.Line(34,28,34,73));g.strokeCircle(34,18,12);g.strokeLineShape(new Phaser.Geom.Line(34,40,16,57));g.strokeLineShape(new Phaser.Geom.Line(34,40,52,57));g.strokeLineShape(new Phaser.Geom.Line(34,70,20,96));g.strokeLineShape(new Phaser.Geom.Line(34,70,51,96))}else{g.fillStyle(kind==='hero'?0x263343:kind==='ghoul'?0x4b4e3e:0x3f4247).fillEllipse(34,60,35,66);g.fillStyle(skin).fillCircle(34,21,14);g.fillStyle(0x19191c).fillRect(22,8,26,7);g.fillStyle(kind==='hero'?0x191c20:0x303035).fillRect(13,38,10,46).fillRect(46,38,10,46);g.fillStyle(0x17191e).fillRect(20,85,12,24).fillRect(39,85,12,24);if(kind==='hero'){g.fillStyle(0x0a0c10).fillRect(42,31,27,17);g.fillStyle(0x67717b).fillRect(63,35,9,9);g.fillStyle(0x9ba2a7).fillRect(48,25,8,8)}if(kind==='knight'){g.lineStyle(3,0x92979b).strokeCircle(34,21,16);g.fillStyle(0x7b2028).fillRect(52,41,12,45)}}t.draw(g);t.saveTexture(key);g.destroy();t.destroy()}
class BlackHouse extends Phaser.Scene{
constructor(){super('BlackHouse');this.health=C.player?.maxHealth||5;this.captured=0;this.film=C.film?.max||100;this.beamPulse=0;this.dead=false;this.stageClear=false;this.checkpoint=170;this.emptyUntil=0;this.totalTargets=(C.horror?.spawns||[]).length||7}
preload(){if(A.courtyard)this.load.image('courtyard',A.courtyard);for(const type of ['hero','skeleton','ghoul','knight']){if(!A[type])continue;const f=type==='hero'?C.player?.frame:C.enemies?.[type]?.frame;if(f)this.load.spritesheet(type+'Real',A[type],{frameWidth:f.width,frameHeight:f.height})}}
create(){const worldW=C.horror?.worldWidth||4300;this.physics.world.setBounds(0,0,worldW,720);this.cameras.main.setBounds(0,0,worldW,720);this.cameras.main.setBackgroundColor('#070910');for(const type of ['hero','skeleton','ghoul','knight'])if(!this.textures.exists(type+'Real'))makeFallback(this,type+'Fallback',type);this.makeWorld();this.makeAnims();this.makePlayer();this.makeEnemies();this.makeFX();this.makeInput();this.makeCamera();this.makeStageUI();this.updateHud()}
makeWorld(){const worldW=C.horror?.worldWidth||4300;if(this.textures.exists('courtyard')){for(let i=0;i<6;i++)this.add.image(i*900,350,'courtyard').setOrigin(0,.5).setDisplaySize(960,498).setScrollFactor(.16).setAlpha(.52).setTint(0x566987).setDepth(-30);for(let i=0;i<6;i++)this.add.image(i*900,395,'courtyard').setOrigin(0,.5).setDisplaySize(960,498).setScrollFactor(.42).setAlpha(.34).setTint(0x8291a8).setDepth(-18)}this.add.circle(1030,120,85,0xcbd9f5,.74).setScrollFactor(.07).setDepth(-40);this.add.circle(1060,95,78,0x0b1021,.93).setScrollFactor(.07).setDepth(-39);for(let i=0;i<24;i++)this.add.ellipse(i*230,470+(i%3)*31,420,56,0xb5c0d0,.025).setScrollFactor(.32+(i%3)*.07).setDepth(-7);this.solids=this.physics.add.staticGroup();const floorY=C.horror?.floorY||610;const floor=this.add.rectangle(worldW/2,floorY+40,worldW,120,0x111116).setAlpha(.95).setDepth(1);this.physics.add.existing(floor,true);this.solids.add(floor);for(let x=0;x<worldW;x+=80){this.add.rectangle(x+40,floorY-27,80,18,0x322d35).setStrokeStyle(1,0x5b505a).setDepth(2);this.add.rectangle(x+13,floorY-10+(x/80%2)*6,23,8,0x1f1b21).setDepth(2)}(C.horror?.platforms||[]).forEach(([x,y,w])=>{const p=this.add.rectangle(x,y,w,24,0x2b2630).setStrokeStyle(2,0x71606e).setDepth(3);this.physics.add.existing(p,true);this.solids.add(p);for(let q=0;q<w;q+=42)this.add.rectangle(x-w/2+q+18,y+10,31,5,0x17141a).setDepth(3)});for(let i=0;i<19;i++){const x=170+i*235;this.add.rectangle(x,560,20,78,0x35303a).setStrokeStyle(2,0x5b535f).setDepth(1);this.add.ellipse(x,520,48,21,0x45404a).setStrokeStyle(2,0x6d6570).setDepth(1)}for(let i=0;i<17;i++){const x=110+i*265;this.add.rectangle(x,542,5,35,0x584638).setDepth(4);this.add.circle(x,521,6,0xffc56f,.95).setDepth(4);this.add.circle(x,521,28,0xff9a48,.08).setBlendMode(Phaser.BlendModes.ADD).setDepth(3)}const cp=C.horror?.checkpointX||2250;this.add.rectangle(cp,548,6,78,0x68606f,.55).setDepth(2);this.add.circle(cp,505,13,0xb9d6e8,.5).setDepth(2)}
makeAnims(){if(this.textures.exists('heroReal')){const a=C.player?.animations?.walk||{start:0,end:5,rate:10};if(!this.anims.exists('hero-walk'))this.anims.create({key:'hero-walk',frames:this.anims.generateFrameNumbers('heroReal',{start:a.start||0,end:a.end??5}),frameRate:a.rate||10,repeat:-1})}for(const type of ['skeleton','ghoul','knight']){const tex=type+'Real',count=C.enemies?.[type]?.frame?.count||6;if(this.textures.exists(tex)&&!this.anims.exists(type+'-walk'))this.anims.create({key:type+'-walk',frames:this.anims.generateFrameNumbers(tex,{start:0,end:count-1}),frameRate:C.enemies?.[type]?.walkRate||6,repeat:-1})}}
makePlayer(){const real=this.textures.exists('heroReal'),tex=real?'heroReal':'heroFallback';this.player=this.physics.add.sprite(170,520,tex,0).setDepth(9).setCollideWorldBounds(true);this.player.setScale(real?(C.player?.scale||.82):1);this.player.body.setSize(real?48:38,real?104:87).setOffset(real?29:18,real?18:10);this.physics.add.collider(this.player,this.solids);this.player.setData('inv',false)}
makeEnemies(){this.enemies=this.physics.add.group();const spawns=C.horror?.spawns||[];spawns.forEach(s=>this.spawn({type:s[0],x:s[1],y:s[2]}));this.physics.add.collider(this.enemies,this.solids);this.physics.add.overlap(this.player,this.enemies,(p,e)=>this.hurt(e));this.time.addEvent({delay:520,loop:true,callback:()=>this.enemyThink()})}
spawn(s){const real=this.textures.exists(s.type+'Real'),tex=real?s.type+'Real':s.type+'Fallback',cfg=C.enemies?.[s.type]||{};const e=this.enemies.create(s.x,s.y,tex,0).setDepth(9);e.setScale(real?(cfg.scale||.8):1);e.body.setSize(real?52:40,real?(s.type==='knight'?112:102):88).setOffset(real?35:15,real?20:8);e.setData('type',s.type);e.setData('capture',0);e.setData('resistance',cfg.resistance||1);e.setData('baseScale',e.scaleX);e.setData('stunned',0);e.setData('bar',this.add.graphics().setDepth(12));return e}
makeFX(){this.beam=this.add.graphics().setDepth(7);this.rings=this.add.graphics().setDepth(8);this.captureBars=this.add.graphics().setDepth(12);this.particles=this.add.particles(0,0,'__DEFAULT',{speed:{min:30,max:120},lifespan:380,quantity:0,scale:{start:.055,end:0},blendMode:'ADD'}).setDepth(13)}
makeInput(){this.cursors=this.input.keyboard.createCursorKeys();this.keys=this.input.keyboard.addKeys('A,D,W,SPACE');document.querySelectorAll('#touch button').forEach(b=>{const k=b.dataset.k,on=e=>{e.preventDefault();ac();input[k]=true},off=e=>{e.preventDefault();input[k]=false};b.addEventListener('pointerdown',on);b.addEventListener('pointerup',off);b.addEventListener('pointercancel',off);b.addEventListener('pointerleave',off)});const fs=document.getElementById('fullscreen');if(fs)fs.onclick=()=>{const el=document.documentElement;(el.requestFullscreen||el.webkitRequestFullscreen)?.call(el);ac()};window.addEventListener('blur',()=>Object.keys(input).forEach(k=>input[k]=false));document.body.addEventListener('pointerdown',()=>{ac();if(!musicTimer)music()},{once:true})}
makeCamera(){this.cameras.main.startFollow(this.player,true,.09,.09,-170,35);this.cameras.main.roundPixels=true;this.cameras.main.setDeadzone(130,75)}
makeStageUI(){this.notice=this.add.text(640,108,'',{fontFamily:'monospace',fontSize:'22px',fontStyle:'bold',color:'#e8debd',stroke:'#08080d',strokeThickness:5,align:'center'}).setOrigin(.5).setScrollFactor(0).setDepth(50).setAlpha(0)}
showNotice(text,duration=1100){this.notice.setText(text).setAlpha(1);this.tweens.killTweensOf(this.notice);this.tweens.add({targets:this.notice,alpha:0,delay:duration,duration:350})}
enemyThink(){if(this.dead||this.stageClear)return;this.enemies.children.iterate(e=>{if(!e?.active)return;if(e.getData('stunned')>0){e.setVelocityX(0);return}const dx=this.player.x-e.x,dist=Math.abs(dx),type=e.getData('type'),speed=C.enemies?.[type]?.speed||45;if(dist<560){e.setVelocityX(Phaser.Math.Clamp(dx*.22,-speed,speed));e.setFlipX(dx<0);const anim=type+'-walk';if(this.anims.exists(anim))e.play(anim,true)}else e.setVelocityX(Math.sin((this.time.now+e.x)*.0015)*12)})}
hurt(e){if(this.player.getData('inv')||this.dead||this.stageClear)return;this.player.setData('inv',true);this.health--;sfx('hurt');this.player.setVelocityY(-210);this.player.setVelocityX(this.player.x<e.x?-210:210);this.cameras.main.shake(140,.007);this.tweens.add({targets:this.player,alpha:.2,yoyo:true,repeat:5,duration:65,onComplete:()=>{this.player.alpha=1;this.player.setData('inv',false)}});if(this.health<=0)this.respawn();this.updateHud()}
respawn(){this.dead=true;this.time.delayedCall(350,()=>{this.health=C.player?.maxHealth||5;this.film=C.film?.max||100;this.player.setPosition(this.checkpoint,500).setVelocity(0,0);this.dead=false;this.updateHud()})}
update(time,dtMs){if(this.dead||this.stageClear)return;const dt=Math.min(dtMs/1000,.05),left=input.left||this.cursors.left.isDown||this.keys.A.isDown,right=input.right||this.cursors.right.isDown||this.keys.D.isDown,jump=input.jump||this.cursors.up.isDown||this.keys.W.isDown,beamHeld=input.beam||this.cursors.space.isDown||this.keys.SPACE.isDown,canBeam=beamHeld&&this.film>0&&time>=this.emptyUntil;const speed=canBeam?(C.player?.captureMoveSpeed||92):(C.player?.speed||225);if(left){this.player.setVelocityX(-speed);this.player.setFlipX(true)}else if(right){this.player.setVelocityX(speed);this.player.setFlipX(false)}else this.player.setVelocityX(this.player.body.velocity.x*.70);const moving=Math.abs(this.player.body.velocity.x)>15;if(moving&&!canBeam&&this.anims.exists('hero-walk'))this.player.play('hero-walk',true);else if(this.player.anims)this.player.anims.stop();if(jump&&this.player.body.blocked.down&&!this.jumpLatch&&!canBeam){this.player.setVelocityY(C.player?.jumpVelocity||-405);sfx('jump');this.jumpLatch=true}if(!jump)this.jumpLatch=false;const cp=C.horror?.checkpointX||2250;if(this.checkpoint<cp&&this.player.x>cp){this.checkpoint=cp;sfx('checkpoint');this.showNotice('CHECKPOINT · EAST COURTYARD')}if(canBeam)this.capture(dt);else{this.beam.clear();this.rings.clear();this.enemies.children.iterate(e=>{if(e?.active)e.setData('stunned',Math.max(0,e.getData('stunned')-dt))});this.film=Math.min(C.film?.max||100,this.film+dt*(C.film?.recoverPerSecond||8))}if(beamHeld&&this.film<=0&&time>=this.emptyUntil){this.emptyUntil=time+(C.film?.emptyLockMs||450);sfx('empty');this.showNotice('FILM RECHARGING',500)}this.drawCaptureBars();this.updateHud()}
capture(dt){this.film=Math.max(0,this.film-dt*(C.film?.drainPerSecond||11));const face=this.player.flipX?-1:1,lensX=this.player.x+face*44,lensY=this.player.y-17,range=C.capture?.range||470,half=C.capture?.spread||150,endX=lensX+face*range;this.beam.clear();this.rings.clear();this.beam.fillStyle(C.capture?.beamColor||0x8ce8ff,C.capture?.beamAlpha||.13);this.beam.lineStyle(2,0xcaf5ff,.55);this.beam.beginPath().moveTo(lensX,lensY).lineTo(endX,lensY-half).lineTo(endX,lensY+half).closePath().fillPath().strokePath();for(let r=70;r<range;r+=84){const t=r/range;this.rings.lineStyle(1,0xbceeff,.18);this.rings.strokeEllipse(lensX+face*r,lensY,12+52*t,34+half*1.15*t)}if(this.time.now-this.beamPulse>(C.capture?.pulseMs||90)){sfx('beam');this.beamPulse=this.time.now}this.enemies.children.iterate(e=>{if(!e?.active)return;const dx=e.x-lensX,dy=e.y-lensY,forward=dx*face;if(forward<=5||forward>range)return;const allowed=(forward/range)*half+20;if(Math.abs(dy)>allowed)return;e.setData('stunned',.15);const resistance=e.getData('resistance')||1,pull=(C.capture?.pullStrength||340)/resistance;e.setVelocityX(-Math.sign(dx)*pull*Math.max(.25,1-forward/range));e.setVelocityY(Phaser.Math.Clamp(-dy*2.5,-100,100));let cap=Math.min(1.2,e.getData('capture')+dt*(C.capture?.baseRate||.82)/resistance);e.setData('capture',cap);const base=e.getData('baseScale')||1,shrink=Phaser.Math.Clamp(1-cap*.36,.46,1);e.setScale(base*shrink);e.setAlpha(1-cap*.34);e.setAngle(Math.sin(this.time.now*.025+e.x)*cap*5);if(Math.random()<.16)this.particles.emitParticleAt(e.x,e.y,1);if(cap>=1||Phaser.Math.Distance.Between(e.x,e.y,lensX,lensY)<38)this.captureEnemy(e)})}
drawCaptureBars(){this.captureBars.clear();this.enemies.children.iterate(e=>{if(!e?.active)return;const cap=e.getData('capture')||0;if(cap<=.02)return;const w=48,h=5,x=e.x-w/2,y=e.y-72;this.captureBars.fillStyle(0x05070a,.78).fillRect(x-2,y-2,w+4,h+4);this.captureBars.fillStyle(0x9deaff,.9).fillRect(x,y,w*Math.min(1,cap),h)})}
captureEnemy(e){if(!e.active)return;this.captured++;this.film=Math.min(C.film?.max||100,this.film+(C.film?.captureReward||13));sfx('capture');this.cameras.main.flash(90,120,210,255,false);this.cameras.main.shake(90,.004);this.particles.emitParticleAt(e.x,e.y,14);const bar=e.getData('bar');if(bar)bar.destroy();e.disableBody(true,true);this.showNotice(`${e.getData('type').toUpperCase()} CAPTURED`,350);if(this.captured>=this.totalTargets)this.completeStage();this.updateHud()}
completeStage(){this.stageClear=true;this.beam.clear();this.rings.clear();sfx('clear');this.player.setVelocity(0,0);this.cameras.main.flash(220,210,230,255,false);this.showNotice('REEL 01 COMPLETE · THE BLACK HOUSE',2600);setTimeout(()=>{const s=document.getElementById('status');if(s)s.innerHTML='THE BLACK HOUSE &nbsp; <span class="film">REEL 01 COMPLETE</span>'},300)}
updateHud(){const s=document.getElementById('status');if(!s)return;const max=C.player?.maxHealth||5;s.innerHTML=`THE BLACK HOUSE &nbsp; <span class="life">LIFE ${'■'.repeat(Math.max(0,this.health))}${'□'.repeat(Math.max(0,max-this.health))}</span> &nbsp; <span class="film">FILM ${Math.round(this.film)}%</span> &nbsp; CAPTURED ${this.captured}/${this.totalTargets}`}
}
new Phaser.Game({type:Phaser.AUTO,parent:'game',width:1280,height:720,backgroundColor:'#06070b',pixelArt:true,roundPixels:true,physics:{default:'arcade',arcade:{gravity:{y:900},debug:false}},scale:{mode:Phaser.Scale.RESIZE,autoCenter:Phaser.Scale.CENTER_BOTH},scene:[BlackHouse],render:{antialias:false,pixelArt:true,roundPixels:true}});
})();