(()=>{
const C=window.MWCAM_CONFIG||{},A=window.MWCAM_ASSETS||{},E=window.MWCAM_ENVIRONMENT||{layers:[]},M=window.MWCAM_ENEMY_ATLAS||{frameWidth:128,frameHeight:128,rows:{skeleton:0,ghoul:4,vampire:8,monster:12,werewolf:16,ghost:20}},TYPES=['skeleton','ghoul','vampire','monster','werewolf','ghost'],BODIES={skeleton:{w:44,h:94,ox:42,oy:24},ghoul:{w:54,h:92,ox:37,oy:27},vampire:{w:46,h:98,ox:41,oy:22},monster:{w:72,h:108,ox:28,oy:16},werewolf:{w:66,h:104,ox:31,oy:18},ghost:{w:50,h:86,ox:39,oy:24}},touch={left:false,right:false,jump:false,beam:false};
class GothicHorror extends Phaser.Scene{
constructor(){super('GothicHorror');this.C=C;this.touch=touch;this.health=C.player?.maxHealth||5;this.film=C.film?.max||100;this.captured=0;this.dead=false;this.jumpLatch=false;this.playerState='idle';this.hurtUntil=0;this.recoilUntil=0;this.coarse=matchMedia('(pointer:coarse)').matches;}
preload(){(E.layers||[]).forEach(l=>{if(l?.key&&l?.file)this.load.image('env-'+l.key,l.file)});this.load.spritesheet('hero',A.hero,{frameWidth:C.player.frame.width,frameHeight:C.player.frame.height});this.load.spritesheet('enemyAtlas',A.enemyAtlas,{frameWidth:M.frameWidth||128,frameHeight:M.frameHeight||128});}
createEnvironment(){const W=C.horror.worldWidth,H=720;this.environmentLayers=[];(E.layers||[]).forEach(l=>{const key='env-'+l.key;if(!this.textures.exists(key))return;const tex=this.textures.get(key).getSourceImage(),sw=tex.width||1280,sh=tex.height||720,scale=(H/sh)*(l.heightScale??1),tw=Math.max(1,Math.round(sw*scale)),coverage=1280+W*Math.max(0,1-(l.scrollFactor??1))+tw*2,count=l.repeat===false?1:Math.ceil(coverage/tw);for(let i=0;i<count;i++){const img=this.add.image(i*tw,l.y??H,key).setOrigin(0,1).setScale(scale).setAlpha(l.alpha??1).setScrollFactor(l.scrollFactor??1,1).setDepth(l.depth??0);img.texture.setFilter(Phaser.Textures.FilterMode.NEAREST);this.environmentLayers.push(img)}})}
createAtmosphere(){const W=C.horror.worldWidth;this.haze=this.add.rectangle(640,310,1280,410,0x7183a4,.055).setOrigin(.5).setScrollFactor(0).setDepth(E.atmosphere?.moonDepth??-55);this.fog=[];const bands=this.coarse?[[450,.11,.10],[555,.07,.22]]:[[420,.16,.08],[500,.11,.14],[570,.08,.23]];bands.forEach(([y,a,s],row)=>{const n=this.coarse?5:8;for(let i=0;i<n;i++){const f=this.add.rectangle(i*760-300,y+((i*19)%38),220+((i*47+row*31)%180),12+((i*13)%18),0x9ba6b7,a).setOrigin(0,.5).setScrollFactor(s,1).setDepth((E.atmosphere?.fogDepth??14)-row);f.setData('drift',row===0?4:3+row);f.setData('span',W+900);this.fog.push(f)}});this.practicals=[];[840,1580,2320,3110,3870].forEach((x,i)=>{const g=this.add.rectangle(x,535-(i%2)*46,8,16,0xf0a85c,.28).setDepth(E.atmosphere?.practicalLightDepth??12);g.setData('phase',i*211);this.practicals.push(g)})}
create(){const W=C.horror.worldWidth;this.physics.world.setBounds(0,0,W,720);this.cameras.main.setBounds(0,0,W,720);this.cameras.main.setBackgroundColor('#070910');this.createEnvironment();this.createAtmosphere();this.solids=this.physics.add.staticGroup();const floor=this.add.rectangle(W/2,C.horror.floorY+45,W,110,0,0).setVisible(false);this.physics.add.existing(floor,true);this.solids.add(floor);(C.horror.platforms||[]).forEach(([x,y,w])=>{const p=this.add.rectangle(x,y,w+18,20,0,0).setVisible(false);this.physics.add.existing(p,true);this.solids.add(p)});this.makeAnimations();this.player=this.physics.add.sprite(170,500,'hero',0).setScale(C.player.scale).setDepth(8).setCollideWorldBounds(true);this.player.body.setSize(46,100).setOffset(41,22);this.physics.add.collider(this.player,this.solids);this.enemies=this.physics.add.group();(C.horror.spawns||[]).forEach(([t,x,y])=>this.spawn(t,x,y));this.physics.add.collider(this.enemies,this.solids);this.physics.add.overlap(this.player,this.enemies,(p,e)=>{if(e.getData('state')==='attack')window.MWCAM_GAMEPLAY.hurt(this,e)});this.beam=this.add.graphics().setDepth(7);this.bars=this.add.graphics().setDepth(12);this.captureFX=this.add.graphics().setDepth(10);this.cursors=this.input.keyboard.createCursorKeys();this.keys=this.input.keyboard.addKeys('A,D,W,SPACE');const cam=C.camera||{};this.cameras.main.startFollow(this.player,true,cam.followLerpX??.105,cam.followLerpY??.095,cam.followOffsetX??-205,cam.followOffsetY??28);this.cameras.main.roundPixels=true;this.cameras.main.setDeadzone(cam.deadzoneW??150,cam.deadzoneH??82);this.bindTouch();this.bindLifecycle();window.MWCAM_GAMEPLAY.setPlayerState(this,'idle');this.updateHud()}
frameRange(t){const s=Number(M.rows?.[t]);return Number.isFinite(s)?{start:s,end:s+3}:null}
makeAnimations(){this.anims.create({key:'hero-walk',frames:this.anims.generateFrameNumbers('hero',{start:0,end:7}),frameRate:C.player.animations.walk.rate,repeat:-1});TYPES.forEach(t=>{const r=this.frameRange(t),cfg=C.enemies?.[t];if(r&&cfg)this.anims.create({key:t+'-walk',frames:this.anims.generateFrameNumbers('enemyAtlas',r),frameRate:cfg.walkRate,repeat:-1})})}
spawn(t,x,y){const cfg=C.enemies?.[t],r=this.frameRange(t),b=BODIES[t];if(!cfg||!r||!b)return;const e=this.enemies.create(x,y,'enemyAtlas',r.start).setScale(cfg.scale).setDepth(8);e.setData({type:t,capture:0,resistance:cfg.resistance,baseY:y,baseScale:cfg.scale,state:'walk',nextAttack:0});e.body.setSize(b.w,b.h).setOffset(b.ox,b.oy);if(cfg.floating){e.body.setAllowGravity(false);e.body.checkCollision.down=false}e.play(t+'-walk');return e}
clearInputs(){touch.left=touch.right=touch.jump=touch.beam=false;this.jumpLatch=false;if(this.player?.body)this.player.setVelocityX(0)}
bindLifecycle(){const clear=()=>this.clearInputs();window.addEventListener('blur',clear,{passive:true});document.addEventListener('visibilitychange',()=>{if(document.hidden)clear()},{passive:true});window.addEventListener('orientationchange',clear,{passive:true});}
bindTouch(){document.querySelectorAll('#touch button').forEach(b=>{const k=b.dataset.k,on=e=>{e.preventDefault();touch[k]=true;b.setPointerCapture?.(e.pointerId)},off=e=>{e.preventDefault();touch[k]=false};b.addEventListener('pointerdown',on,{passive:false});b.addEventListener('pointerup',off,{passive:false});b.addEventListener('pointercancel',off,{passive:false});b.addEventListener('lostpointercapture',off,{passive:false})});const fs=document.getElementById('fullscreen');if(fs)fs.onclick=()=>document.documentElement.requestFullscreen?.()}
updateAtmosphere(time,dt){const camX=this.cameras.main.scrollX;for(const f of this.fog||[]){f.x+=f.getData('drift')*dt;if(f.x>f.getData('span'))f.x=-500;f.visible=Math.abs(f.x-camX)<1800}for(const p of this.practicals||[]){p.visible=Math.abs(p.x-(camX+640))<900;if(!p.visible)continue;const s=Math.floor((time+p.getData('phase'))/90)%6;p.setAlpha([.20,.31,.24,.36,.27,.22][s]);p.setScale(s===3?1.18:1,s===1?1.12:1)}}
updateHud(){const el=document.getElementById('status');if(el)el.innerHTML=`GOTHIC HORROR · <span class="life">LIFE ${this.health}</span> · <span class="film">FILM ${Math.round(this.film)}</span> · CAPTURED ${this.captured}/${(C.horror.spawns||[]).length}`}
update(time,dt){window.MWCAM_GAMEPLAY.update(this,time,dt)}
}
new Phaser.Game({type:Phaser.AUTO,parent:'game',width:1280,height:720,pixelArt:true,antialias:false,roundPixels:true,powerPreference:'high-performance',disableContextMenu:true,fps:{target:60,min:30,smoothStep:true},physics:{default:'arcade',arcade:{gravity:{y:900},debug:false}},scale:{mode:Phaser.Scale.FIT,autoCenter:Phaser.Scale.CENTER_BOTH},scene:[GothicHorror]});
})();