'use strict';
(()=>{const C=GOTHIC_CONFIG,G=GOTHIC;
class GothicHorror extends Phaser.Scene{
 constructor(){super('GothicHorror');}
 init(data={}){this.player=null;this.transitioning=false;this.stageIndex=data.stage??0;this.stage=C.stages[this.stageIndex];this.edition=C.edition;this.autoStart=data.auto??false;this.health=data.health??C.hero.health;this.film=data.film??100;this.captured=0;this.total=data.total??0;this.checkpoint=C.spawnX;this.clock=0;this.tick=0;this.invUntil=0;this.hurtUntil=0;this.recoilUntil=0;this.flashUntil=0;this.flashHeld=false;this.emptyUntil=0;this.lastFilmUse=0;this.jumpHeld=false;this.jumpBuffered=-1;this.lastGround=-1000;this.playerState=null;this.assetErrors=[];this.enemies=[];this.projectiles=[];this.stats=data.stats||{captures:0,damage:0,flashes:0,blocked:0,dodged:0,attacks:0,checkpoints:0,respawns:0,pickups:0,stages:0};G.scene=this;G.phase='loading';G.clearInputs();}
 preload(){this.load.on('loaderror',f=>this.assetErrors.push(f.key));for(const a of GOTHIC_ASSETS){if(this.textures.exists(a.key))continue;if(a.frames)this.load.spritesheet(a.key,a.data,{frameWidth:a.frameWidth,frameHeight:a.frameHeight});else this.load.image(a.key,a.data);}}
 create(){if(this.assetErrors.length){G.fail('Artwork failed: '+this.assetErrors.join(', '));return;}for(const a of GOTHIC_ASSETS){const tex=this.textures.get(a.key),im=tex.getSourceImage();if(im.width!==a.width||im.height!==a.height||(a.frames&&tex.frameTotal-1!==a.frames)){G.fail('Invalid asset dimensions/frames: '+a.key);return;}tex.setFilter(Phaser.Textures.FilterMode.NEAREST);}
 GOTHIC_WORLD.build(this);this.animations();this.player=this.physics.add.sprite(C.spawnX,C.floorY+6,'hero-brace').setOrigin(.5,1).setDepth(20).setCollideWorldBounds(true);this.player.body.setSize(28,78).setOffset(42,28);this.player.setMaxVelocity(C.hero.speed,600);GOTHIC_WORLD.connect(this);
 for(const [type,x]of this.stage.enemies)this.spawn(type,x);
 this.beam=this.add.graphics().setDepth(23);this.fx=this.add.graphics().setDepth(24);this.light=this.add.image(0,0,'camera-light').setOrigin(0,.5).setBlendMode(Phaser.BlendModes.ADD).setDepth(21).setVisible(false);this.halo=this.add.image(0,0,'lens-halo').setScale(.55).setBlendMode(Phaser.BlendModes.ADD).setDepth(22);
 this.cursors=this.input.keyboard.createCursorKeys();this.keys=this.input.keyboard.addKeys('A,D,W,SPACE,C,P,R,X,SHIFT');
 this.pauseKey=()=>G.pause('manual',!G.pauseReasons.has('manual'));this.restartKey=()=>{G.clearInputs();this.scene.restart({stage:0,auto:true});};this.input.keyboard.on('keydown-P',this.pauseKey);this.input.keyboard.on('keydown-R',this.restartKey);
 this.cameras.main.stopFollow();this.cameras.main.useBounds=false;this.cameras.main.setOrigin(0,0).setZoom(C.renderScale).setScroll(0,0);this.cameras.main.roundPixels=true;this.input.keyboard.addCapture('LEFT,RIGHT,UP,DOWN,SPACE,A,D,W,C,X,SHIFT');GOTHIC_HUD.create(this);GOTHIC_HUD.render(this);for(const o of this.children.list)if(o.type==='Text'){o.setFontSize(parseFloat(o.style.fontSize)*2);o.setScale(.5);}
 this.physics.pause();G.phase='ready';document.getElementById('build').textContent='BUILD R'+this.edition;document.getElementById('edition').textContent='R'+this.edition+' · FOUR STAGES';document.querySelector('[data-input="flash"]').hidden=this.edition<4;
 G.overlay('GOTHIC HORROR','Thirty encounters. Four broken crossings. Film is scarce: collect reels and ride the moving ferries.','PRESS START');document.getElementById('instructions').textContent=G.mobile?'LEFT THUMB MOVES · TAP FILM ON/OFF · JUMP & FLASH ON THE RIGHT':'← → / A D MOVE · ↑ / W JUMP · HOLD SPACE / C TO FILM · X / SHIFT FLASH';G.orientation();if(this.autoStart)G.start();
 this.events.once('shutdown',()=>{this.input.keyboard.off('keydown-P',this.pauseKey);this.input.keyboard.off('keydown-R',this.restartKey);G.clearInputs();this.enemies=[];this.projectiles=[];});
 }
 animations(){for(const[key,count,rate,repeat]of[['hero-stride',12,12,-1],['hero-brace',4,4,-1],['hero-recoil',4,10,0],['hero-jump',4,9,0],['hero-hurt',4,9,0]])if(!this.anims.exists(key))this.anims.create({key,frames:this.anims.generateFrameNumbers(key,{start:0,end:count-1}),frameRate:rate,repeat});for(const type of Object.keys(C.enemies))for(const[state,start,end]of[['walk',0,3],['attack',4,5],['resist',6,7]]){const key=type+'-'+state;if(!this.anims.exists(key))this.anims.create({key,frames:this.anims.generateFrameNumbers(type,{start,end}),frameRate:state==='walk'?6:8,repeat:state==='attack'?0:-1});}}
 spawn(type,x){const cfg=C.enemies[type],e=this.physics.add.sprite(x,cfg.floating?C.floorY-8:C.floorY+6,type).setOrigin(.5,1).setDepth(18).setFlipX(true).setCollideWorldBounds(true);e.body.setSize(type==='monster'?50:34,80).setOffset(type==='monster'?31:39,26);e.setData({type,state:'walk',capture:0,nextAttack:this.edition>=4?180:800,attackAt:0,baseY:C.floorY-8,homeX:x,hit:false,stunUntil:0,attackDir:1});e.body.setAllowGravity(!cfg.floating);if(!cfg.floating)this.physics.add.collider(e,this.solids,null,a=>!['resist','pull','capturing'].includes(a.getData('state')));e.play(type+'-walk');this.enemies.push(e);return e;}
 pose(state){if(this.playerState===state)return;this.playerState=state;this.player.play(state==='walk'?'hero-stride':'hero-'+state,true);}
 toast(text){this.hudToast?.setText(text).setAlpha(1);this.toastUntil=this.clock+1800;}
 damage(enemy,time=this.clock){if(time<this.invUntil||G.phase!=='running')return false;this.health--;this.stats.damage++;this.hurtUntil=time+C.hero.hurtMs;this.invUntil=time+C.hero.invulnerabilityMs;this.player.setVelocity(this.player.x<enemy.x?-140:140,-135);this.pose('hurt');G.audio.play('hurt');if(!matchMedia('(prefers-reduced-motion: reduce)').matches)this.cameras.main.shake(75,.0025);if(this.health<=0)this.respawn();return true;}
 respawn(reason='combat'){this.stats.respawns++;if(reason!=='fall'||this.health<=0){this.health=C.hero.health;this.film=Math.max(this.film,C.film.respawn);}this.lastFilmUse=this.clock;this.emptyUntil=0;this.player.body.reset(this.checkpoint,C.floorY-12);this.player.setVelocity(0);this.invUntil=this.clock+1600;this.hurtUntil=this.clock+200;for(const p of this.projectiles)if(p.active)p.destroy();this.projectiles=[];for(const e of this.enemies)if(e.active&&e.getData('state')!=='capturing'&&Math.abs(e.x-this.checkpoint)<220){e.body.reset(this.checkpoint+260,C.floorY+6);e.setData({state:'walk',nextAttack:this.clock+1900});}this.toast('CHECKPOINT RESTORED');G.clearInputs();}
 capture(e,dt){const cfg=C.enemies[e.getData('type')],c=Math.min(1,e.getData('capture')+dt/cfg.resistance);e.setData('capture',c);const state=c>.42?'pull':'resist';if(e.getData('state')!==state){e.setData('state',state);e.play(e.getData('type')+'-resist');}e.body.setAllowGravity(false);const dir=this.player.flipX?-1:1,x=this.player.x+dir*42,y=this.player.y-45;e.setVelocity(Math.sign(x-e.x)*Math.min(C.capture.pullSpeed,Math.abs(x-e.x)*5)*(c>.42?1:.28),(y-e.y)*c*2);e.setTint(0xdbf3ff).setAngle(Math.round(Math.sin(this.clock*.02)*3*c)).setScale(1-c*.23);
 if(c>=1){e.setData('state','capturing');e.body.enable=false;e.anims.stop();const v=this.add.image(e.x,e.y-40,'spiral').setDepth(25).setBlendMode(Phaser.BlendModes.ADD);this.tweens.add({targets:[e,v],x,y:y-10,scaleX:.06,scaleY:.06,alpha:0,duration:250,onComplete:()=>{e.destroy();v.destroy();}});this.captured++;this.total++;this.stats.captures++;this.film=Math.min(100,this.film+C.film.reward);this.recoilUntil=this.clock+140;this.pose('recoil');G.audio.play('capture');this.exitLabel.setText(this.captured===this.stage.enemies.length?'GATE OPEN →':'SEAL: '+(this.stage.enemies.length-this.captured));if(this.captured===this.stage.enemies.length){this.gate.setTint(0xc2e9f5);this.toast('STAGE CLEAR · REACH THE GATE');}}
 }
 release(e){const cfg=C.enemies[e.getData('type')];if(['resist','pull'].includes(e.getData('state'))){e.setData('state','walk');e.setScale(1).setAngle(0).clearTint();e.body.setAllowGravity(!cfg.floating);e.play(e.getData('type')+'-walk');}}
 basicAI(e){const cfg=C.enemies[e.getData('type')],dx=this.player.x-e.x,dy=this.player.body.center.y-e.body.center.y,time=this.clock;if(e.getData('state')==='attack'){const age=time-e.getData('attackAt');e.setVelocityX(0);if(age>420&&!e.getData('hit')&&Math.abs(dx)<61&&Math.abs(dy)<48){e.setData('hit',true);this.damage(e,time);}if(age>700){e.setData('state','walk');e.play(e.getData('type')+'-walk');}return;}if(Math.abs(dx)<63&&Math.abs(dy)<48&&time>=e.getData('nextAttack')){e.setData({state:'attack',attackAt:time,nextAttack:time+1400,hit:false});e.play(e.getData('type')+'-attack');return;}e.setFlipX(dx<0);e.setVelocityX(Math.abs(dx)<360?Math.sign(dx)*cfg.speed:0);if(cfg.floating)e.setVelocityY((e.getData('baseY')+Math.sin(time*.002)*12-e.y)*3);}
 drawBeam(active){const dir=this.player.flipX?-1:1,x=this.player.x+dir*26,y=this.player.y-66;this.halo.setPosition(x,y).setAlpha(active?.9:.13);this.light.setPosition(x,y).setScale(dir*C.capture.range/300,.82).setVisible(active).setAlpha(.85+.07*Math.sin(this.clock*.027));if(!active)return;const g=this.beam;for(let band=-2;band<=2;band++){g.lineStyle(1,0xbfeaff,band===0?.85:.35);g.beginPath().moveTo(x,y);for(let j=1;j<=22;j++){const t=j/22;g.lineTo(Math.round(x+dir*C.capture.range*t),Math.round(y+band*23*t+Math.sin(this.clock*.012+j+band)*2));}g.strokePath();}g.fillStyle(0xf6fcff,.9);for(let i=0;i<28;i++){const t=(i*.137+this.clock*.00055)%1;g.fillRect(Math.round(x+dir*C.capture.range*(1-t)),Math.round(y+Math.sin(i*2.4)*(1-t)*48),1,1);}}
 advance(){if(this.transitioning)return;this.transitioning=true;this.stats.stages++;G.phase='transition';this.physics.pause();G.clearInputs();if(this.stageIndex===C.stages.length-1){G.phase='complete';G.overlay('GOTHIC HORROR — ON FILM','Courtyard, cathedral, catacombs and ramparts are clear. All thirty creatures captured.','PLAY AGAIN');return;}this.cameras.main.fadeOut(260,5,10,18);this.time.delayedCall(280,()=>this.scene.restart({stage:this.stageIndex+1,auto:true,health:Math.min(5,this.health+1),total:this.total,film:this.film,stats:this.stats}));}
 update(_time,delta){if(G.phase!=='running'||!this.player)return;const dt=Math.min(delta/1000,.045);this.clock+=dt*1000;this.tick++;const now=this.clock,p=this.player,t=G.inputs,grounded=p.body.blocked.down||p.body.touching.down;this.onPlatform=null;const cam=this.cameras.main,view=G.viewWidth||640,target=Phaser.Math.Clamp(p.x-view*.35,0,Math.max(0,this.stage.worldWidth-view));cam.scrollX=Phaser.Math.Clamp(cam.scrollX+(target-cam.scrollX)*(1-Math.exp(-dt*8)),0,Math.max(0,this.stage.worldWidth-view));cam.scrollY=0;
 const left=t.left||this.cursors.left.isDown||this.keys.A.isDown,right=t.right||this.cursors.right.isDown||this.keys.D.isDown,jump=t.jump||this.cursors.up.isDown||this.keys.W.isDown,held=t.beam||this.keys.SPACE.isDown||this.keys.C.isDown,flash=t.flash||this.keys.X.isDown||this.keys.SHIFT.isDown;
 if(this.edition>=4&&(G.flashQueued||(flash&&!this.flashHeld))&&window.GOTHIC_COMBAT)GOTHIC_COMBAT.flash(this);G.flashQueued=false;this.flashHeld=flash;
 const beam=held&&this.film>0&&now>=this.emptyUntil&&now>=this.hurtUntil;this.beaming=beam;if(grounded)this.lastGround=now;if(G.jumpQueued||(jump&&!this.jumpHeld))this.jumpBuffered=now;G.jumpQueued=false;this.jumpHeld=jump;
 if(now>=this.hurtUntil){const dir=Number(right)-Number(left),target=dir*(beam?C.hero.filmSpeed:C.hero.speed),a=(dir?C.hero.acceleration:C.hero.drag)*dt;p.setVelocityX(p.body.velocity.x+Phaser.Math.Clamp(target-p.body.velocity.x,-a,a));if(dir)p.setFlipX(dir<0);if(this.jumpBuffered>=0&&now-this.jumpBuffered<C.hero.jumpBufferMs&&now-this.lastGround<C.hero.coyoteMs){p.setVelocityY(C.hero.jump);this.jumpBuffered=-1;this.lastGround=-1000;G.audio.play('jump');}this.pose(now<this.recoilUntil?'recoil':!grounded?'jump':Math.abs(p.body.velocity.x)>8?'walk':'brace');if(this.playerState==='walk')p.anims.timeScale=Math.max(.45,Math.abs(p.body.velocity.x)/C.hero.speed);else p.anims.timeScale=1;}
 p.setAlpha(now<this.invUntil?(Math.floor(now/90)%2?.55:1):1);this.beam.clear();this.fx.clear();if(beam){this.film=Math.max(0,this.film-C.film.drain*dt);this.lastFilmUse=now;}else if(now-this.lastFilmUse>C.film.recoverDelay&&this.film<C.film.recoveryCap){this.film=Math.min(C.film.recoveryCap,this.film+C.film.recover*dt);}if(beam&&this.film===0){this.emptyUntil=now+C.film.emptyLockMs;G.stopFilming();this.toast('EMPTY · FIND A GOLD FILM REEL');}this.drawBeam(beam);
 for(const e of this.enemies){if(!e.active||e.getData('state')==='capturing')continue;const cfg=C.enemies[e.getData('type')],dx=(e.x-p.x)*(p.flipX?-1:1),dy=Math.abs(e.body.center.y-p.body.center.y),targeted=beam&&dx>8&&dx<C.capture.range+26&&dy<C.capture.halfHeight,allowed=this.edition<4||!window.GOTHIC_COMBAT||GOTHIC_COMBAT.canCapture(this,e);
 if(targeted&&allowed)this.capture(e,dt);else{this.release(e);e.setData('capture',Math.max(0,e.getData('capture')-dt*C.capture.releaseDecay));if(this.edition>=4&&window.GOTHIC_COMBAT)GOTHIC_COMBAT.updateEnemy(this,e,dt);else this.basicAI(e);}
 if(e.y>460){e.body.reset(e.getData('homeX'),C.floorY-20);e.setVelocity(0);e.setData('state','walk');}
 const c=e.getData('capture');if(c>0){this.fx.lineStyle(1,0xbbebff,.8).strokeRect(e.x-18,e.y-e.displayHeight+10,36,4);this.fx.fillStyle(0xc1edff).fillRect(e.x-17,e.y-e.displayHeight+11,34*c,2);}}
 if(this.edition>=4&&window.GOTHIC_COMBAT)GOTHIC_COMBAT.updateProjectiles(this,dt);GOTHIC_WORLD.update(this,dt);
 if(p.y>435){this.health--;this.stats.damage++;this.respawn('fall');}if(p.x>this.stage.checkpoint&&this.checkpoint===C.spawnX){this.checkpoint=this.stage.checkpoint;this.stats.checkpoints++;this.film=Math.min(100,this.film+C.film.checkpoint);this.checkpointLabel.setText('◆ SAVED').setColor('#c7e6bb');this.toast('CHECKPOINT · FILM +20');G.audio.play('checkpoint');}
 if(p.x>this.stage.exit.x-22&&this.captured===this.stage.enemies.length&&Math.abs(p.body.bottom-this.exitTop)<24)this.advance();
 if(this.toastUntil&&now>this.toastUntil)this.hudToast.setText('');GOTHIC_HUD.render(this);
 }
}
window.GOTHIC_SCENE=GothicHorror;
})();
