'use strict';
window.GOTHIC={phase:'loading',errors:[],inputs:{left:false,right:false,jump:false,beam:false,flash:false},pauseReasons:new Set(),scene:null,viewWidth:640,mobile:matchMedia('(any-pointer:coarse)').matches};
(()=>{const G=GOTHIC,$=id=>document.getElementById(id),pointers=new Map();let padPointer=null,padDirection=0,latched=false,installEvent=null;
const defaults={movement:'pad',film:'toggle',size:'1'};try{G.preferences={...defaults,...JSON.parse(localStorage.getItem('gothic-controls-r5')||'{}')}}catch{G.preferences={...defaults}}
const sync=()=>{for(const k of Object.keys(G.inputs))G.inputs[k]=[...pointers.values()].includes(k);G.inputs.left ||=padDirection<0;G.inputs.right ||=padDirection>0;G.inputs.beam ||=latched;document.querySelectorAll('[data-input]').forEach(el=>el.classList.toggle('pressed',G.inputs[el.dataset.input]));const film=document.querySelector('.film');film.classList.toggle('latched',latched);$('film-label').textContent=latched?'FILM ON':'FILM';};
G.overlay=(title,copy,button)=>{$('overlay').hidden=false;$('overlay-title').textContent=title;$('overlay-copy').textContent=copy;$('start').hidden=!button;if(button)$('start').textContent=button;};
G.fail=message=>{G.errors.push(String(message));G.phase='error';G.scene?.physics?.pause();G.overlay('BUILD COULD NOT START',String(message));$('reload').hidden=false;console.error(message);};
window.addEventListener('error',e=>G.fail(e.message));window.addEventListener('unhandledrejection',e=>G.fail(e.reason?.message||e.reason));
G.clearInputs=()=>{G.flashQueued=false;G.jumpQueued=false;pointers.clear();latched=false;padPointer=null;padDirection=0;$('pad-knob').style.transform='translateX(0)';$('move-pad').classList.remove('active');sync();G.scene?.input?.keyboard?.resetKeys();const p=G.scene?.player;if(p?.active&&p.body?.enable)p.setVelocityX(0);};
G.stopFilming=()=>{latched=false;for(const[id,k]of pointers)if(k==='beam')pointers.delete(id);sync();};
G.pause=(reason,active)=>{active?G.pauseReasons.add(reason):G.pauseReasons.delete(reason);G.clearInputs();const s=G.scene;if(!s||!['running','paused'].includes(G.phase))return;const paused=G.pauseReasons.size>0;G.phase=paused?'paused':'running';if(paused){s.physics.pause();s.tweens.pauseAll();G.overlay(G.pauseReasons.has('portrait')?'ROTATE TO LANDSCAPE':'PAUSED','Film is scarce. Collect the gold reels; wait for the ferry before crossing.',G.pauseReasons.has('portrait')?null:'RESUME');}else{s.physics.resume();s.tweens.resumeAll();$('overlay').hidden=true;}s.player?.anims[paused?'pause':'resume']();for(const e of s.enemies||[])if(e.active)e.anims[paused?'pause':'resume']();};
G.start=()=>{G.audio?.unlock();if(G.pauseReasons.has('portrait'))return;if(G.phase==='ready'){G.phase='running';G.scene.physics.resume();$('overlay').hidden=true;if(G.pauseReasons.size)G.pause('start',false);}else if(G.phase==='complete'){G.scene.scene.restart({stage:0,auto:true});}else if(G.phase==='paused'){for(const k of ['manual','focus','display'])G.pauseReasons.delete(k);G.pause('hidden',document.hidden);}$('game').focus({preventScroll:true});};
$('start').onclick=G.start;$('reload').onclick=()=>location.reload();$('pause').onclick=()=>G.pause('manual',!G.pauseReasons.has('manual'));
G.displayHelp=(message)=>{G.pause('display',true);$('display-help').hidden=false;const ios=/iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);$('display-copy').textContent=message||(ios?'On iPhone: in Safari, open Share → Add to Home Screen. Leave “Open as Web App” on, then tap Add. Launch the new Movie Camera icon and turn the phone sideways. This opens the game without Safari’s address and tab bars.':'Use your browser’s Install app or Add to Home Screen option for an app-sized view. Browser fullscreen is not available in this context.');$('install-app').hidden=!installEvent;};
G.fullscreen=async()=>{try{const full=document.fullscreenElement||document.webkitFullscreenElement;if(full){const exit=document.exitFullscreen||document.webkitExitFullscreen;if(exit)await exit.call(document);return;}const el=$('shell'),request=el.requestFullscreen||el.webkitRequestFullscreen;if(request&&(document.fullscreenEnabled!==false)){await request.call(el);try{await screen.orientation?.lock?.('landscape')}catch{}G.layout();return;}if(navigator.standalone||matchMedia('(display-mode: standalone)').matches){G.displayHelp('You are already playing in the standalone app view. Rotate to landscape to use the available screen.');return;}G.displayHelp();}catch{G.displayHelp();}};
$('fullscreen').onclick=G.fullscreen;$('close-display').onclick=()=>{$('display-help').hidden=true;G.pause('display',false);};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e;});$('install-app').onclick=async()=>{if(!installEvent)return;try{await installEvent.prompt();await installEvent.userChoice;}finally{installEvent=null;$('install-app').hidden=true;}};
G.layout=()=>{const rect=$('stage').getBoundingClientRect();G.viewWidth=G.mobile?Math.max(640,Math.min(1000,Math.round(rect.width/Math.max(1,rect.height)*360))):640;if(G.game?.scale){const density=GOTHIC_CONFIG.renderScale;if(G.game.scale.width!==G.viewWidth*density)G.game.scale.resize(G.viewWidth*density,360*density);const s=G.scene;if(s?.cameras?.main){s.cameras.main.setViewport(0,0,G.viewWidth*density,360*density).setOrigin(0,0).setZoom(density);if(s.hudGraphics)GOTHIC_HUD.layout(s);}}};
G.orientation=()=>{const portrait=G.mobile&&innerHeight>innerWidth;G.pause('portrait',portrait);if(G.phase==='ready'){$('start').hidden=portrait;$('overlay-copy').textContent=portrait?'Turn your phone sideways. The thumb pad moves; JUMP is on your right.':'Thirty encounters. Four broken crossings. Collect film and ride the moving ferries.';}G.layout();};
window.addEventListener('resize',G.orientation);window.visualViewport?.addEventListener('resize',G.layout);document.addEventListener('fullscreenchange',G.layout);document.addEventListener('webkitfullscreenchange',G.layout);window.addEventListener('blur',()=>G.pause('focus',true));window.addEventListener('focus',()=>G.pause('focus',false));document.addEventListener('visibilitychange',()=>G.pause('hidden',document.hidden));
window.addEventListener('keydown',e=>{if(/^(INPUT|SELECT|TEXTAREA)$/.test(e.target.tagName))return;if(['ArrowUp','KeyW'].includes(e.code)&&G.phase==='running'&&!e.repeat)G.jumpQueued=true;if(['KeyX','ShiftLeft','ShiftRight'].includes(e.code)&&G.phase==='running'&&!e.repeat)G.flashQueued=true;if((e.code==='Enter'||e.code==='Space')&&['ready','complete'].includes(G.phase)){e.preventDefault();G.start();}if(e.code==='Escape'&&G.phase==='paused')G.start();},{passive:false});
for(const el of document.querySelectorAll('[data-input]')){const key=el.dataset.input;el.addEventListener('pointerdown',e=>{e.preventDefault();if(G.phase!=='running')return;if(key==='beam'&&G.preferences.film==='toggle'){latched=!latched;}else pointers.set(e.pointerId,key);if(key==='flash')G.flashQueued=true;if(key==='jump')G.jumpQueued=true;sync();el.setPointerCapture(e.pointerId);},{passive:false});const off=e=>{pointers.delete(e.pointerId);sync();};for(const ev of ['pointerup','pointercancel','lostpointercapture'])el.addEventListener(ev,off);}
const pad=$('move-pad'),move=e=>{if(e.pointerId!==padPointer)return;const box=pad.getBoundingClientRect(),offset=Math.max(-42,Math.min(42,(e.clientX-(box.x+box.width/2))*142/box.width));padDirection=Math.abs(offset)<13?0:Math.sign(offset);$('pad-knob').style.transform=`translateX(${offset}px)`;sync();};pad.addEventListener('pointerdown',e=>{e.preventDefault();if(G.phase!=='running'||padPointer!==null)return;padPointer=e.pointerId;pad.setPointerCapture(e.pointerId);pad.classList.add('active');move(e);},{passive:false});pad.addEventListener('pointermove',move);const endPad=e=>{if(e.pointerId!==padPointer)return;padPointer=null;padDirection=0;$('pad-knob').style.transform='translateX(0)';pad.classList.remove('active');sync();};for(const ev of ['pointerup','pointercancel','lostpointercapture'])pad.addEventListener(ev,endPad);
G.applyPreferences=()=>{if(!['pad','arrows'].includes(G.preferences.movement))G.preferences.movement='pad';if(!['toggle','hold'].includes(G.preferences.film))G.preferences.film='toggle';if(!['1','1.2'].includes(G.preferences.size))G.preferences.size='1';document.body.dataset.controls=G.preferences.movement;$('touch').style.setProperty('--control-scale',G.preferences.size);$('control-mode').value=G.preferences.movement;$('film-mode').value=G.preferences.film;$('control-size').value=G.preferences.size;G.clearInputs();};for(const [id,key]of[['control-mode','movement'],['film-mode','film'],['control-size','size']])$(id).onchange=()=>{G.preferences[key]=$(id).value;try{localStorage.setItem('gothic-controls-r5',JSON.stringify(G.preferences))}catch{}G.applyPreferences();};G.applyPreferences();
if('serviceWorker'in navigator&&location.protocol==='https:')window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js',{scope:'./'}).catch(()=>{}));
})();
