'use strict';
window.GOTHIC_WORLD={
 build(s){const C=GOTHIC_CONFIG,W=s.stage.worldWidth,vw=GOTHIC.viewWidth||640;s.physics.world.setBounds(0,-80,W,560);s.cameras.main.setOrigin(0,0).setZoom(C.renderScale).setBounds(0,0,W,360).setBackgroundColor('#07101b');s.backdrops=[];
 const sf=s.stage.scroll,count=Math.ceil((W*sf+vw)/640)+1;for(let i=0;i<count;i++)s.backdrops.push(s.add.image(i*640,0,s.stage.background).setOrigin(0).setDisplaySize(640,360).setFlipX(i%2===1).setScrollFactor(sf,0).setDepth(-30));
 // Real source art is layered independently; no full opaque foreground over the actor.
 if(s.stage.id!=='courtyard')for(let x=250;x<W;x+=570)s.add.image(x,313,'arch').setOrigin(.5,1).setAlpha(s.stage.id==='ramparts'?.72:.24).setDepth(-12);
 if(['courtyard','ramparts'].includes(s.stage.id))for(let x=50;x<W;x+=680)s.add.image(x,316,'branch').setOrigin(.5,1).setAlpha(.65).setDepth(-7).setScale(.9);
 s.solids=s.physics.add.staticGroup();s.platforms=[];s.pickups=[];s.riddenPlatforms=new Set();
 const segments=[];let cursor=0;for(const[a,b]of s.stage.gaps||[]){segments.push([cursor,a]);cursor=b;}segments.push([cursor,W]);s.floorSegments=segments;
 for(const[x0,x1]of segments){const z=s.add.zone((x0+x1)/2,C.floorY+30,x1-x0,60);s.physics.add.existing(z,true);s.solids.add(z);for(let x=x0;x<x1;x+=448){const width=Math.min(448,x1-x);s.add.image(x,C.floorY,'stone').setOrigin(0).setCrop(0,0,width,44).setDepth(-4);}}
 s.pitArt=s.add.graphics().setDepth(-3);for(const[a,b]of s.stage.gaps||[]){for(let band=0;band<6;band++)s.pitArt.fillStyle(0x01040b,.38+band*.1).fillRect(a,316+band*8,b-a,8);s.add.image(a-12,313,'column').setOrigin(.5,0).setDisplaySize(24,116).setDepth(-2);s.add.image(b+12,313,'column').setOrigin(.5,0).setDisplaySize(24,116).setDepth(-2);s.add.text(a-83,233,'WAIT FOR THE FERRY\nJUMP ABOARD',{fontFamily:'monospace',fontSize:'8px',align:'center',color:'#cfbd8f',stroke:'#080c15',strokeThickness:3}).setOrigin(.5).setDepth(30);}
 for(const def of s.stage.platforms)this.platform(s,def);if(s.stage.ferry)this.platform(s,{...s.stage.ferry,ferry:true});s.chainArt=s.add.graphics().setDepth(-1);
 for(const p of s.stage.pickups){const obj=s.add.image(p.x,p.y,p.kind==='heart'?'heart':'film-reel').setDepth(14).setScale(p.kind==='heart'?1.5:.75);s.pickups.push({obj,...p,baseY:p.y});}
 s.checkpointLabel=s.add.text(s.stage.checkpoint,282,'◆ SAVE + FILM',{fontFamily:'monospace',fontSize:'8px',color:'#a8c5a0',stroke:'#102019',strokeThickness:3}).setOrigin(.5).setDepth(32);s.exitTop=s.stage.exit.top;
 s.gate=s.add.image(s.stage.exit.x,s.exitTop,'arch').setOrigin(.5,1).setTint(0x7b8c9d).setDepth(12);s.exitLabel=s.add.text(s.stage.exit.x,s.exitTop-152,'SEAL: '+s.stage.enemies.length,{fontFamily:'monospace',fontSize:'8px',color:'#d8c393',stroke:'#0a1422',strokeThickness:3}).setOrigin(.5).setDepth(30);
 s.stageBanner=s.add.text(vw/2,92,s.stage.name,{fontFamily:'Georgia',fontSize:'20px',color:'#e9dab7',stroke:'#07101b',strokeThickness:4}).setOrigin(.5).setScrollFactor(0).setDepth(120);s.tweens.add({targets:s.stageBanner,alpha:0,delay:1300,duration:800});
 s.lights=[];for(let x=240;x<W;x+=510){if((s.stage.gaps||[]).some(([a,b])=>x>a-40&&x<b+40))continue;s.add.image(x,269,'torch').setOrigin(.5,1).setDepth(-6).setScale(.63);s.lights.push(s.add.image(x,230,'lens-halo').setTint(s.stage.palette).setAlpha(.30).setScale(.68).setBlendMode(Phaser.BlendModes.ADD).setDepth(-5));}
 s.mist=[];for(let row=0;row<2;row++)for(let i=0;i<Math.ceil(vw/512)+2;i++)s.mist.push(s.add.image(i*510-300,282+row*37,'mist').setOrigin(0,.5).setDisplaySize(540,50).setScrollFactor(.4+row*.35,0).setDepth(row?-1:-9).setAlpha(row?.30:.44).setData('baseX',i*510-300).setData('phase',i+row*2));
 },
 platform(s,def){const w=def.width,z=s.add.zone(def.x,def.top+6,w,12);s.physics.add.existing(z,!def.motion);z.body.setSize(w,12);if(def.motion){z.body.setAllowGravity(false).setImmovable(true).setFriction(1,1);}z.body.checkCollision.down=false;z.body.checkCollision.left=false;z.body.checkCollision.right=false;const art=s.add.image(def.x-w/2,def.top,'stone').setOrigin(0).setCrop(0,0,w,18).setDepth(2);const p={zone:z,art,def,collapseAt:0,returnAt:0,startX:def.x,startY:def.top+6};if(def.ferry)art.setTint(0xcab99b);s.platforms.push(p);return p;},
 connect(s){s.physics.add.collider(s.player,s.solids);for(const p of s.platforms)s.physics.add.collider(s.player,p.zone,()=>{s.onPlatform=p;if(p.def.ferry&&!s.riddenPlatforms.has(p)){s.riddenPlatforms.add(p);s.stats.ferryBoardings=(s.stats.ferryBoardings||0)+1;s.toast('STAY ABOARD · JUMP TO THE FAR BANK');}if(p.def.crumble&&!p.collapseAt)p.collapseAt=s.clock+900;},(a,b)=>b.body.enable&&a.body.velocity.y>=-1&&a.body.prev.y+a.body.height<=b.body.top+8);},
 update(s,dt){const now=s.clock;s.chainArt.clear();for(const p of s.platforms){const m=p.def.motion,b=p.zone.body;if(m&&b.enable){const axis=m.axis,target=(axis==='x'?p.startX:p.startY)+Math.sin(now*.001*m.speed/m.distance)*m.distance,position=axis==='x'?p.zone.x:p.zone.y,v=Phaser.Math.Clamp((target-position)*8,-m.speed,m.speed);if(axis==='x')b.setVelocity(v,0);else b.setVelocity(0,v);}
 p.art.setPosition(p.zone.x-p.def.width/2,p.zone.y-6);if(p.def.ferry){for(const x of[p.zone.x-p.def.width*.34,p.zone.x+p.def.width*.34])for(let y=72;y<p.zone.y-8;y+=7){s.chainArt.lineStyle(1,0xa38c64,.8).strokeRect(Math.round(x),y,2,5);}}
 if(p.collapseAt){p.art.setTint(Math.floor(now/100)%2?0xcaa078:0xffffff);if(now>p.collapseAt){b.enable=false;p.art.setVisible(false);p.collapseAt=0;p.returnAt=now+3300;}}if(p.returnAt&&now>p.returnAt){b.enable=true;p.art.setVisible(true).clearTint();p.returnAt=0;}}
 for(const p of s.pickups){if(!p.obj.active)continue;p.obj.y=p.baseY+Math.sin(now*.004)*3;if(Math.abs(s.player.x-p.x)<27&&Math.abs(s.player.body.center.y-p.obj.y)<44){if(p.kind==='heart'&&s.health>=GOTHIC_CONFIG.hero.health)continue;if(p.kind==='film'&&s.film>=86)continue;if(p.kind==='heart')s.health=Math.min(GOTHIC_CONFIG.hero.health,s.health+1);else s.film=Math.min(100,s.film+GOTHIC_CONFIG.film.pickup);s.toast(p.kind==='heart'?'LIFE +1':'FILM +25');p.obj.destroy();GOTHIC.audio.play('checkpoint');s.stats.pickups++;}}
 for(let i=0;i<s.lights.length;i++)s.lights[i].setAlpha(.24+.055*Math.sin(now*.009+i*3));for(const m of s.mist)m.x=m.getData('baseX')+Math.sin(now*.00025+m.getData('phase'))*80;
 }
};
