'use strict';
window.GOTHIC={phase:'loading',errors:[],inputs:{left:false,right:false,jump:false,beam:false,flash:false},pauseReasons:new Set(),run:{stage:0,total:0},scene:null};
(()=>{const G=GOTHIC,$=id=>document.getElementById(id),pointers=new Map();
G.overlay=(title,copy,button)=>{$('overlay').hidden=false;$('overlay-title').textContent=title;$('overlay-copy').textContent=copy;$('start').hidden=!button;if(button)$('start').textContent=button;};
G.fail=message=>{G.errors.push(String(message));G.phase='error';G.scene?.physics?.pause();G.overlay('BUILD COULD NOT START',String(message));$('reload').hidden=false;console.error(message);};
window.addEventListener('error',e=>G.fail(e.message));window.addEventListener('unhandledrejection',e=>G.fail(e.reason?.message||e.reason));
G.clearInputs=()=>{G.flashQueued=false;pointers.clear();Object.keys(G.inputs).forEach(k=>G.inputs[k]=false);document.querySelectorAll('[data-input]').forEach(e=>e.classList.remove('pressed'));G.scene?.input?.keyboard?.resetKeys();if(G.scene?.player?.body)G.scene.player.setVelocityX(0);};
G.pause=(reason,active)=>{active?G.pauseReasons.add(reason):G.pauseReasons.delete(reason);G.clearInputs();const s=G.scene;if(!s||!['running','paused'].includes(G.phase))return;const paused=G.pauseReasons.size>0;G.phase=paused?'paused':'running';if(paused){s.physics.pause();s.tweens.pauseAll();G.overlay(G.pauseReasons.has('portrait')?'ROTATE TO LANDSCAPE':'PAUSED','Your film and progress are safe.',G.pauseReasons.has('portrait')?null:'RESUME');}else{s.physics.resume();s.tweens.resumeAll();$('overlay').hidden=true;}s.player?.anims[paused?'pause':'resume']();for(const e of s.enemies||[])if(e.active)e.anims[paused?'pause':'resume']();};
G.start=()=>{G.audio?.unlock();if(G.pauseReasons.has('portrait'))return;if(G.phase==='ready'){G.phase='running';G.scene.physics.resume();$('overlay').hidden=true;if(G.pauseReasons.size)G.pause('start',false);}else if(G.phase==='complete'){G.run={stage:0,total:0};G.scene.scene.restart({stage:0,auto:true});}else if(G.phase==='paused'){G.pauseReasons.delete('manual');G.pauseReasons.delete('focus');G.pause('hidden',document.hidden);}};
$('start').onclick=G.start;$('reload').onclick=()=>location.reload();$('pause').onclick=()=>G.pause('manual',!G.pauseReasons.has('manual'));
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('shell').requestFullscreen();}catch{}};
G.fullscreen=()=>$('fullscreen').click();if(!$('shell').requestFullscreen)$('fullscreen').hidden=true;
const orient=()=>{const portrait=matchMedia('(any-pointer:coarse)').matches&&innerHeight>innerWidth;G.pause('portrait',portrait);if(G.phase==='ready'){$('start').hidden=portrait;$('overlay-copy').textContent=portrait?'Rotate your phone to landscape.':GOTHIC_CONFIG?.edition===4?'Four stages. Twelve creatures. Film them, dodge their attacks, and reach the far gate.':'Four stages. Twelve creatures. Follow the light into the cathedral.';}};
window.addEventListener('resize',orient);window.addEventListener('blur',()=>G.pause('focus',true));window.addEventListener('focus',()=>G.pause('focus',false));document.addEventListener('visibilitychange',()=>G.pause('hidden',document.hidden));G.orientation=orient;
window.addEventListener('keydown',e=>{if(['KeyX','ShiftLeft','ShiftRight'].includes(e.code)&&G.phase==='running'&&!e.repeat)G.flashQueued=true;if((e.code==='Enter'||e.code==='Space')&&['ready','complete'].includes(G.phase)){e.preventDefault();G.start();}if(e.code==='Escape'&&G.phase==='paused')G.start();});
for(const el of document.querySelectorAll('[data-input]')){const key=el.dataset.input,off=e=>{pointers.delete(e.pointerId);G.inputs[key]=[...pointers.values()].includes(key);el.classList.toggle('pressed',G.inputs[key]);};el.addEventListener('pointerdown',e=>{e.preventDefault();if(G.phase!=='running')return;pointers.set(e.pointerId,key);G.inputs[key]=true;if(key==='flash')G.flashQueued=true;el.classList.add('pressed');el.setPointerCapture(e.pointerId);},{passive:false});for(const ev of ['pointerup','pointercancel','lostpointercapture'])el.addEventListener(ev,off);}
})();
